// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/resources/protos/trace.proto

package com.dd.agent.pb;

public interface APISpanOrBuilder extends
    // @@protoc_insertion_point(interface_extends:pb.APISpan)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string service = 1;</code>
   * @return The service.
   */
  java.lang.String getService();
  /**
   * <code>string service = 1;</code>
   * @return The bytes for service.
   */
  com.google.protobuf.ByteString
      getServiceBytes();

  /**
   * <code>string name = 2;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 2;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string resource = 3;</code>
   * @return The resource.
   */
  java.lang.String getResource();
  /**
   * <code>string resource = 3;</code>
   * @return The bytes for resource.
   */
  com.google.protobuf.ByteString
      getResourceBytes();

  /**
   * <code>uint64 traceID = 4;</code>
   * @return The traceID.
   */
  long getTraceID();

  /**
   * <code>uint64 spanID = 5;</code>
   * @return The spanID.
   */
  long getSpanID();

  /**
   * <code>uint64 parentID = 6;</code>
   * @return The parentID.
   */
  long getParentID();

  /**
   * <code>int64 start = 7;</code>
   * @return The start.
   */
  long getStart();

  /**
   * <code>int64 duration = 8;</code>
   * @return The duration.
   */
  long getDuration();

  /**
   * <code>int32 error = 9;</code>
   * @return The error.
   */
  int getError();

  /**
   * <code>map&lt;string, string&gt; meta = 10;</code>
   */
  int getMetaCount();
  /**
   * <code>map&lt;string, string&gt; meta = 10;</code>
   */
  boolean containsMeta(
      java.lang.String key);
  /**
   * Use {@link #getMetaMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, java.lang.String>
  getMeta();
  /**
   * <code>map&lt;string, string&gt; meta = 10;</code>
   */
  java.util.Map<java.lang.String, java.lang.String>
  getMetaMap();
  /**
   * <code>map&lt;string, string&gt; meta = 10;</code>
   */
  /* nullable */
java.lang.String getMetaOrDefault(
      java.lang.String key,
      /* nullable */
java.lang.String defaultValue);
  /**
   * <code>map&lt;string, string&gt; meta = 10;</code>
   */
  java.lang.String getMetaOrThrow(
      java.lang.String key);

  /**
   * <code>map&lt;string, double&gt; metrics = 11;</code>
   */
  int getMetricsCount();
  /**
   * <code>map&lt;string, double&gt; metrics = 11;</code>
   */
  boolean containsMetrics(
      java.lang.String key);
  /**
   * Use {@link #getMetricsMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, java.lang.Double>
  getMetrics();
  /**
   * <code>map&lt;string, double&gt; metrics = 11;</code>
   */
  java.util.Map<java.lang.String, java.lang.Double>
  getMetricsMap();
  /**
   * <code>map&lt;string, double&gt; metrics = 11;</code>
   */
  double getMetricsOrDefault(
      java.lang.String key,
      double defaultValue);
  /**
   * <code>map&lt;string, double&gt; metrics = 11;</code>
   */
  double getMetricsOrThrow(
      java.lang.String key);

  /**
   * <code>string type = 12;</code>
   * @return The type.
   */
  java.lang.String getType();
  /**
   * <code>string type = 12;</code>
   * @return The bytes for type.
   */
  com.google.protobuf.ByteString
      getTypeBytes();

  /**
   * <code>map&lt;string, bytes&gt; meta_struct = 13;</code>
   */
  int getMetaStructCount();
  /**
   * <code>map&lt;string, bytes&gt; meta_struct = 13;</code>
   */
  boolean containsMetaStruct(
      java.lang.String key);
  /**
   * Use {@link #getMetaStructMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, com.google.protobuf.ByteString>
  getMetaStruct();
  /**
   * <code>map&lt;string, bytes&gt; meta_struct = 13;</code>
   */
  java.util.Map<java.lang.String, com.google.protobuf.ByteString>
  getMetaStructMap();
  /**
   * <code>map&lt;string, bytes&gt; meta_struct = 13;</code>
   */
  /* nullable */
com.google.protobuf.ByteString getMetaStructOrDefault(
      java.lang.String key,
      /* nullable */
com.google.protobuf.ByteString defaultValue);
  /**
   * <code>map&lt;string, bytes&gt; meta_struct = 13;</code>
   */
  com.google.protobuf.ByteString getMetaStructOrThrow(
      java.lang.String key);
}
