// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/resources/protos/trace.proto

package com.dd.agent.pb;

/**
 * Protobuf type {@code pb.APISpan}
 */
public final class APISpan extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:pb.APISpan)
    APISpanOrBuilder {
private static final long serialVersionUID = 0L;
  // Use APISpan.newBuilder() to construct.
  private APISpan(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private APISpan() {
    service_ = "";
    name_ = "";
    resource_ = "";
    type_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new APISpan();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.dd.agent.pb.APITraceProto.internal_static_pb_APISpan_descriptor;
  }

  @SuppressWarnings({"rawtypes"})
  @java.lang.Override
  protected com.google.protobuf.MapField internalGetMapField(
      int number) {
    switch (number) {
      case 10:
        return internalGetMeta();
      case 11:
        return internalGetMetrics();
      case 13:
        return internalGetMetaStruct();
      default:
        throw new RuntimeException(
            "Invalid map field number: " + number);
    }
  }
  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.dd.agent.pb.APITraceProto.internal_static_pb_APISpan_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.dd.agent.pb.APISpan.class, com.dd.agent.pb.APISpan.Builder.class);
  }

  public static final int SERVICE_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object service_ = "";
  /**
   * <code>string service = 1;</code>
   * @return The service.
   */
  @java.lang.Override
  public java.lang.String getService() {
    java.lang.Object ref = service_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      service_ = s;
      return s;
    }
  }
  /**
   * <code>string service = 1;</code>
   * @return The bytes for service.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getServiceBytes() {
    java.lang.Object ref = service_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      service_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int NAME_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object name_ = "";
  /**
   * <code>string name = 2;</code>
   * @return The name.
   */
  @java.lang.Override
  public java.lang.String getName() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      name_ = s;
      return s;
    }
  }
  /**
   * <code>string name = 2;</code>
   * @return The bytes for name.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNameBytes() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int RESOURCE_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object resource_ = "";
  /**
   * <code>string resource = 3;</code>
   * @return The resource.
   */
  @java.lang.Override
  public java.lang.String getResource() {
    java.lang.Object ref = resource_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      resource_ = s;
      return s;
    }
  }
  /**
   * <code>string resource = 3;</code>
   * @return The bytes for resource.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getResourceBytes() {
    java.lang.Object ref = resource_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      resource_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TRACEID_FIELD_NUMBER = 4;
  private long traceID_ = 0L;
  /**
   * <code>uint64 traceID = 4;</code>
   * @return The traceID.
   */
  @java.lang.Override
  public long getTraceID() {
    return traceID_;
  }

  public static final int SPANID_FIELD_NUMBER = 5;
  private long spanID_ = 0L;
  /**
   * <code>uint64 spanID = 5;</code>
   * @return The spanID.
   */
  @java.lang.Override
  public long getSpanID() {
    return spanID_;
  }

  public static final int PARENTID_FIELD_NUMBER = 6;
  private long parentID_ = 0L;
  /**
   * <code>uint64 parentID = 6;</code>
   * @return The parentID.
   */
  @java.lang.Override
  public long getParentID() {
    return parentID_;
  }

  public static final int START_FIELD_NUMBER = 7;
  private long start_ = 0L;
  /**
   * <code>int64 start = 7;</code>
   * @return The start.
   */
  @java.lang.Override
  public long getStart() {
    return start_;
  }

  public static final int DURATION_FIELD_NUMBER = 8;
  private long duration_ = 0L;
  /**
   * <code>int64 duration = 8;</code>
   * @return The duration.
   */
  @java.lang.Override
  public long getDuration() {
    return duration_;
  }

  public static final int ERROR_FIELD_NUMBER = 9;
  private int error_ = 0;
  /**
   * <code>int32 error = 9;</code>
   * @return The error.
   */
  @java.lang.Override
  public int getError() {
    return error_;
  }

  public static final int META_FIELD_NUMBER = 10;
  private static final class MetaDefaultEntryHolder {
    static final com.google.protobuf.MapEntry<
        java.lang.String, java.lang.String> defaultEntry =
            com.google.protobuf.MapEntry
            .<java.lang.String, java.lang.String>newDefaultInstance(
                com.dd.agent.pb.APITraceProto.internal_static_pb_APISpan_MetaEntry_descriptor, 
                com.google.protobuf.WireFormat.FieldType.STRING,
                "",
                com.google.protobuf.WireFormat.FieldType.STRING,
                "");
  }
  @SuppressWarnings("serial")
  private com.google.protobuf.MapField<
      java.lang.String, java.lang.String> meta_;
  private com.google.protobuf.MapField<java.lang.String, java.lang.String>
  internalGetMeta() {
    if (meta_ == null) {
      return com.google.protobuf.MapField.emptyMapField(
          MetaDefaultEntryHolder.defaultEntry);
    }
    return meta_;
  }
  public int getMetaCount() {
    return internalGetMeta().getMap().size();
  }
  /**
   * <code>map&lt;string, string&gt; meta = 10;</code>
   */
  @java.lang.Override
  public boolean containsMeta(
      java.lang.String key) {
    if (key == null) { throw new NullPointerException("map key"); }
    return internalGetMeta().getMap().containsKey(key);
  }
  /**
   * Use {@link #getMetaMap()} instead.
   */
  @java.lang.Override
  @java.lang.Deprecated
  public java.util.Map<java.lang.String, java.lang.String> getMeta() {
    return getMetaMap();
  }
  /**
   * <code>map&lt;string, string&gt; meta = 10;</code>
   */
  @java.lang.Override
  public java.util.Map<java.lang.String, java.lang.String> getMetaMap() {
    return internalGetMeta().getMap();
  }
  /**
   * <code>map&lt;string, string&gt; meta = 10;</code>
   */
  @java.lang.Override
  public /* nullable */
java.lang.String getMetaOrDefault(
      java.lang.String key,
      /* nullable */
java.lang.String defaultValue) {
    if (key == null) { throw new NullPointerException("map key"); }
    java.util.Map<java.lang.String, java.lang.String> map =
        internalGetMeta().getMap();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }
  /**
   * <code>map&lt;string, string&gt; meta = 10;</code>
   */
  @java.lang.Override
  public java.lang.String getMetaOrThrow(
      java.lang.String key) {
    if (key == null) { throw new NullPointerException("map key"); }
    java.util.Map<java.lang.String, java.lang.String> map =
        internalGetMeta().getMap();
    if (!map.containsKey(key)) {
      throw new java.lang.IllegalArgumentException();
    }
    return map.get(key);
  }

  public static final int METRICS_FIELD_NUMBER = 11;
  private static final class MetricsDefaultEntryHolder {
    static final com.google.protobuf.MapEntry<
        java.lang.String, java.lang.Double> defaultEntry =
            com.google.protobuf.MapEntry
            .<java.lang.String, java.lang.Double>newDefaultInstance(
                com.dd.agent.pb.APITraceProto.internal_static_pb_APISpan_MetricsEntry_descriptor, 
                com.google.protobuf.WireFormat.FieldType.STRING,
                "",
                com.google.protobuf.WireFormat.FieldType.DOUBLE,
                0D);
  }
  @SuppressWarnings("serial")
  private com.google.protobuf.MapField<
      java.lang.String, java.lang.Double> metrics_;
  private com.google.protobuf.MapField<java.lang.String, java.lang.Double>
  internalGetMetrics() {
    if (metrics_ == null) {
      return com.google.protobuf.MapField.emptyMapField(
          MetricsDefaultEntryHolder.defaultEntry);
    }
    return metrics_;
  }
  public int getMetricsCount() {
    return internalGetMetrics().getMap().size();
  }
  /**
   * <code>map&lt;string, double&gt; metrics = 11;</code>
   */
  @java.lang.Override
  public boolean containsMetrics(
      java.lang.String key) {
    if (key == null) { throw new NullPointerException("map key"); }
    return internalGetMetrics().getMap().containsKey(key);
  }
  /**
   * Use {@link #getMetricsMap()} instead.
   */
  @java.lang.Override
  @java.lang.Deprecated
  public java.util.Map<java.lang.String, java.lang.Double> getMetrics() {
    return getMetricsMap();
  }
  /**
   * <code>map&lt;string, double&gt; metrics = 11;</code>
   */
  @java.lang.Override
  public java.util.Map<java.lang.String, java.lang.Double> getMetricsMap() {
    return internalGetMetrics().getMap();
  }
  /**
   * <code>map&lt;string, double&gt; metrics = 11;</code>
   */
  @java.lang.Override
  public double getMetricsOrDefault(
      java.lang.String key,
      double defaultValue) {
    if (key == null) { throw new NullPointerException("map key"); }
    java.util.Map<java.lang.String, java.lang.Double> map =
        internalGetMetrics().getMap();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }
  /**
   * <code>map&lt;string, double&gt; metrics = 11;</code>
   */
  @java.lang.Override
  public double getMetricsOrThrow(
      java.lang.String key) {
    if (key == null) { throw new NullPointerException("map key"); }
    java.util.Map<java.lang.String, java.lang.Double> map =
        internalGetMetrics().getMap();
    if (!map.containsKey(key)) {
      throw new java.lang.IllegalArgumentException();
    }
    return map.get(key);
  }

  public static final int TYPE_FIELD_NUMBER = 12;
  @SuppressWarnings("serial")
  private volatile java.lang.Object type_ = "";
  /**
   * <code>string type = 12;</code>
   * @return The type.
   */
  @java.lang.Override
  public java.lang.String getType() {
    java.lang.Object ref = type_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      type_ = s;
      return s;
    }
  }
  /**
   * <code>string type = 12;</code>
   * @return The bytes for type.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTypeBytes() {
    java.lang.Object ref = type_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      type_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int META_STRUCT_FIELD_NUMBER = 13;
  private static final class MetaStructDefaultEntryHolder {
    static final com.google.protobuf.MapEntry<
        java.lang.String, com.google.protobuf.ByteString> defaultEntry =
            com.google.protobuf.MapEntry
            .<java.lang.String, com.google.protobuf.ByteString>newDefaultInstance(
                com.dd.agent.pb.APITraceProto.internal_static_pb_APISpan_MetaStructEntry_descriptor, 
                com.google.protobuf.WireFormat.FieldType.STRING,
                "",
                com.google.protobuf.WireFormat.FieldType.BYTES,
                com.google.protobuf.ByteString.EMPTY);
  }
  @SuppressWarnings("serial")
  private com.google.protobuf.MapField<
      java.lang.String, com.google.protobuf.ByteString> metaStruct_;
  private com.google.protobuf.MapField<java.lang.String, com.google.protobuf.ByteString>
  internalGetMetaStruct() {
    if (metaStruct_ == null) {
      return com.google.protobuf.MapField.emptyMapField(
          MetaStructDefaultEntryHolder.defaultEntry);
    }
    return metaStruct_;
  }
  public int getMetaStructCount() {
    return internalGetMetaStruct().getMap().size();
  }
  /**
   * <code>map&lt;string, bytes&gt; meta_struct = 13;</code>
   */
  @java.lang.Override
  public boolean containsMetaStruct(
      java.lang.String key) {
    if (key == null) { throw new NullPointerException("map key"); }
    return internalGetMetaStruct().getMap().containsKey(key);
  }
  /**
   * Use {@link #getMetaStructMap()} instead.
   */
  @java.lang.Override
  @java.lang.Deprecated
  public java.util.Map<java.lang.String, com.google.protobuf.ByteString> getMetaStruct() {
    return getMetaStructMap();
  }
  /**
   * <code>map&lt;string, bytes&gt; meta_struct = 13;</code>
   */
  @java.lang.Override
  public java.util.Map<java.lang.String, com.google.protobuf.ByteString> getMetaStructMap() {
    return internalGetMetaStruct().getMap();
  }
  /**
   * <code>map&lt;string, bytes&gt; meta_struct = 13;</code>
   */
  @java.lang.Override
  public /* nullable */
com.google.protobuf.ByteString getMetaStructOrDefault(
      java.lang.String key,
      /* nullable */
com.google.protobuf.ByteString defaultValue) {
    if (key == null) { throw new NullPointerException("map key"); }
    java.util.Map<java.lang.String, com.google.protobuf.ByteString> map =
        internalGetMetaStruct().getMap();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }
  /**
   * <code>map&lt;string, bytes&gt; meta_struct = 13;</code>
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getMetaStructOrThrow(
      java.lang.String key) {
    if (key == null) { throw new NullPointerException("map key"); }
    java.util.Map<java.lang.String, com.google.protobuf.ByteString> map =
        internalGetMetaStruct().getMap();
    if (!map.containsKey(key)) {
      throw new java.lang.IllegalArgumentException();
    }
    return map.get(key);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(service_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, service_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(resource_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, resource_);
    }
    if (traceID_ != 0L) {
      output.writeUInt64(4, traceID_);
    }
    if (spanID_ != 0L) {
      output.writeUInt64(5, spanID_);
    }
    if (parentID_ != 0L) {
      output.writeUInt64(6, parentID_);
    }
    if (start_ != 0L) {
      output.writeInt64(7, start_);
    }
    if (duration_ != 0L) {
      output.writeInt64(8, duration_);
    }
    if (error_ != 0) {
      output.writeInt32(9, error_);
    }
    com.google.protobuf.GeneratedMessageV3
      .serializeStringMapTo(
        output,
        internalGetMeta(),
        MetaDefaultEntryHolder.defaultEntry,
        10);
    com.google.protobuf.GeneratedMessageV3
      .serializeStringMapTo(
        output,
        internalGetMetrics(),
        MetricsDefaultEntryHolder.defaultEntry,
        11);
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(type_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 12, type_);
    }
    com.google.protobuf.GeneratedMessageV3
      .serializeStringMapTo(
        output,
        internalGetMetaStruct(),
        MetaStructDefaultEntryHolder.defaultEntry,
        13);
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(service_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, service_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(resource_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, resource_);
    }
    if (traceID_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(4, traceID_);
    }
    if (spanID_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(5, spanID_);
    }
    if (parentID_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(6, parentID_);
    }
    if (start_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(7, start_);
    }
    if (duration_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(8, duration_);
    }
    if (error_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(9, error_);
    }
    for (java.util.Map.Entry<java.lang.String, java.lang.String> entry
         : internalGetMeta().getMap().entrySet()) {
      com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
      meta__ = MetaDefaultEntryHolder.defaultEntry.newBuilderForType()
          .setKey(entry.getKey())
          .setValue(entry.getValue())
          .build();
      size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(10, meta__);
    }
    for (java.util.Map.Entry<java.lang.String, java.lang.Double> entry
         : internalGetMetrics().getMap().entrySet()) {
      com.google.protobuf.MapEntry<java.lang.String, java.lang.Double>
      metrics__ = MetricsDefaultEntryHolder.defaultEntry.newBuilderForType()
          .setKey(entry.getKey())
          .setValue(entry.getValue())
          .build();
      size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(11, metrics__);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(type_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(12, type_);
    }
    for (java.util.Map.Entry<java.lang.String, com.google.protobuf.ByteString> entry
         : internalGetMetaStruct().getMap().entrySet()) {
      com.google.protobuf.MapEntry<java.lang.String, com.google.protobuf.ByteString>
      metaStruct__ = MetaStructDefaultEntryHolder.defaultEntry.newBuilderForType()
          .setKey(entry.getKey())
          .setValue(entry.getValue())
          .build();
      size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(13, metaStruct__);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.dd.agent.pb.APISpan)) {
      return super.equals(obj);
    }
    com.dd.agent.pb.APISpan other = (com.dd.agent.pb.APISpan) obj;

    if (!getService()
        .equals(other.getService())) return false;
    if (!getName()
        .equals(other.getName())) return false;
    if (!getResource()
        .equals(other.getResource())) return false;
    if (getTraceID()
        != other.getTraceID()) return false;
    if (getSpanID()
        != other.getSpanID()) return false;
    if (getParentID()
        != other.getParentID()) return false;
    if (getStart()
        != other.getStart()) return false;
    if (getDuration()
        != other.getDuration()) return false;
    if (getError()
        != other.getError()) return false;
    if (!internalGetMeta().equals(
        other.internalGetMeta())) return false;
    if (!internalGetMetrics().equals(
        other.internalGetMetrics())) return false;
    if (!getType()
        .equals(other.getType())) return false;
    if (!internalGetMetaStruct().equals(
        other.internalGetMetaStruct())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + SERVICE_FIELD_NUMBER;
    hash = (53 * hash) + getService().hashCode();
    hash = (37 * hash) + NAME_FIELD_NUMBER;
    hash = (53 * hash) + getName().hashCode();
    hash = (37 * hash) + RESOURCE_FIELD_NUMBER;
    hash = (53 * hash) + getResource().hashCode();
    hash = (37 * hash) + TRACEID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getTraceID());
    hash = (37 * hash) + SPANID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getSpanID());
    hash = (37 * hash) + PARENTID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getParentID());
    hash = (37 * hash) + START_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getStart());
    hash = (37 * hash) + DURATION_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getDuration());
    hash = (37 * hash) + ERROR_FIELD_NUMBER;
    hash = (53 * hash) + getError();
    if (!internalGetMeta().getMap().isEmpty()) {
      hash = (37 * hash) + META_FIELD_NUMBER;
      hash = (53 * hash) + internalGetMeta().hashCode();
    }
    if (!internalGetMetrics().getMap().isEmpty()) {
      hash = (37 * hash) + METRICS_FIELD_NUMBER;
      hash = (53 * hash) + internalGetMetrics().hashCode();
    }
    hash = (37 * hash) + TYPE_FIELD_NUMBER;
    hash = (53 * hash) + getType().hashCode();
    if (!internalGetMetaStruct().getMap().isEmpty()) {
      hash = (37 * hash) + META_STRUCT_FIELD_NUMBER;
      hash = (53 * hash) + internalGetMetaStruct().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.dd.agent.pb.APISpan parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.dd.agent.pb.APISpan parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.dd.agent.pb.APISpan parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.dd.agent.pb.APISpan parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.dd.agent.pb.APISpan parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.dd.agent.pb.APISpan parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.dd.agent.pb.APISpan parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.dd.agent.pb.APISpan parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.dd.agent.pb.APISpan parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.dd.agent.pb.APISpan parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.dd.agent.pb.APISpan parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.dd.agent.pb.APISpan parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.dd.agent.pb.APISpan prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code pb.APISpan}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:pb.APISpan)
      com.dd.agent.pb.APISpanOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.dd.agent.pb.APITraceProto.internal_static_pb_APISpan_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 10:
          return internalGetMeta();
        case 11:
          return internalGetMetrics();
        case 13:
          return internalGetMetaStruct();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMutableMapField(
        int number) {
      switch (number) {
        case 10:
          return internalGetMutableMeta();
        case 11:
          return internalGetMutableMetrics();
        case 13:
          return internalGetMutableMetaStruct();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.dd.agent.pb.APITraceProto.internal_static_pb_APISpan_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.dd.agent.pb.APISpan.class, com.dd.agent.pb.APISpan.Builder.class);
    }

    // Construct using com.dd.agent.pb.APISpan.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      service_ = "";
      name_ = "";
      resource_ = "";
      traceID_ = 0L;
      spanID_ = 0L;
      parentID_ = 0L;
      start_ = 0L;
      duration_ = 0L;
      error_ = 0;
      internalGetMutableMeta().clear();
      internalGetMutableMetrics().clear();
      type_ = "";
      internalGetMutableMetaStruct().clear();
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.dd.agent.pb.APITraceProto.internal_static_pb_APISpan_descriptor;
    }

    @java.lang.Override
    public com.dd.agent.pb.APISpan getDefaultInstanceForType() {
      return com.dd.agent.pb.APISpan.getDefaultInstance();
    }

    @java.lang.Override
    public com.dd.agent.pb.APISpan build() {
      com.dd.agent.pb.APISpan result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.dd.agent.pb.APISpan buildPartial() {
      com.dd.agent.pb.APISpan result = new com.dd.agent.pb.APISpan(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.dd.agent.pb.APISpan result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.service_ = service_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.name_ = name_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.resource_ = resource_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.traceID_ = traceID_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.spanID_ = spanID_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.parentID_ = parentID_;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.start_ = start_;
      }
      if (((from_bitField0_ & 0x00000080) != 0)) {
        result.duration_ = duration_;
      }
      if (((from_bitField0_ & 0x00000100) != 0)) {
        result.error_ = error_;
      }
      if (((from_bitField0_ & 0x00000200) != 0)) {
        result.meta_ = internalGetMeta();
        result.meta_.makeImmutable();
      }
      if (((from_bitField0_ & 0x00000400) != 0)) {
        result.metrics_ = internalGetMetrics();
        result.metrics_.makeImmutable();
      }
      if (((from_bitField0_ & 0x00000800) != 0)) {
        result.type_ = type_;
      }
      if (((from_bitField0_ & 0x00001000) != 0)) {
        result.metaStruct_ = internalGetMetaStruct();
        result.metaStruct_.makeImmutable();
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.dd.agent.pb.APISpan) {
        return mergeFrom((com.dd.agent.pb.APISpan)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.dd.agent.pb.APISpan other) {
      if (other == com.dd.agent.pb.APISpan.getDefaultInstance()) return this;
      if (!other.getService().isEmpty()) {
        service_ = other.service_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.getName().isEmpty()) {
        name_ = other.name_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (!other.getResource().isEmpty()) {
        resource_ = other.resource_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (other.getTraceID() != 0L) {
        setTraceID(other.getTraceID());
      }
      if (other.getSpanID() != 0L) {
        setSpanID(other.getSpanID());
      }
      if (other.getParentID() != 0L) {
        setParentID(other.getParentID());
      }
      if (other.getStart() != 0L) {
        setStart(other.getStart());
      }
      if (other.getDuration() != 0L) {
        setDuration(other.getDuration());
      }
      if (other.getError() != 0) {
        setError(other.getError());
      }
      internalGetMutableMeta().mergeFrom(
          other.internalGetMeta());
      bitField0_ |= 0x00000200;
      internalGetMutableMetrics().mergeFrom(
          other.internalGetMetrics());
      bitField0_ |= 0x00000400;
      if (!other.getType().isEmpty()) {
        type_ = other.type_;
        bitField0_ |= 0x00000800;
        onChanged();
      }
      internalGetMutableMetaStruct().mergeFrom(
          other.internalGetMetaStruct());
      bitField0_ |= 0x00001000;
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              service_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              name_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              resource_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 32: {
              traceID_ = input.readUInt64();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            case 40: {
              spanID_ = input.readUInt64();
              bitField0_ |= 0x00000010;
              break;
            } // case 40
            case 48: {
              parentID_ = input.readUInt64();
              bitField0_ |= 0x00000020;
              break;
            } // case 48
            case 56: {
              start_ = input.readInt64();
              bitField0_ |= 0x00000040;
              break;
            } // case 56
            case 64: {
              duration_ = input.readInt64();
              bitField0_ |= 0x00000080;
              break;
            } // case 64
            case 72: {
              error_ = input.readInt32();
              bitField0_ |= 0x00000100;
              break;
            } // case 72
            case 82: {
              com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
              meta__ = input.readMessage(
                  MetaDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              internalGetMutableMeta().getMutableMap().put(
                  meta__.getKey(), meta__.getValue());
              bitField0_ |= 0x00000200;
              break;
            } // case 82
            case 90: {
              com.google.protobuf.MapEntry<java.lang.String, java.lang.Double>
              metrics__ = input.readMessage(
                  MetricsDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              internalGetMutableMetrics().getMutableMap().put(
                  metrics__.getKey(), metrics__.getValue());
              bitField0_ |= 0x00000400;
              break;
            } // case 90
            case 98: {
              type_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000800;
              break;
            } // case 98
            case 106: {
              com.google.protobuf.MapEntry<java.lang.String, com.google.protobuf.ByteString>
              metaStruct__ = input.readMessage(
                  MetaStructDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              internalGetMutableMetaStruct().getMutableMap().put(
                  metaStruct__.getKey(), metaStruct__.getValue());
              bitField0_ |= 0x00001000;
              break;
            } // case 106
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object service_ = "";
    /**
     * <code>string service = 1;</code>
     * @return The service.
     */
    public java.lang.String getService() {
      java.lang.Object ref = service_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        service_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string service = 1;</code>
     * @return The bytes for service.
     */
    public com.google.protobuf.ByteString
        getServiceBytes() {
      java.lang.Object ref = service_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        service_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string service = 1;</code>
     * @param value The service to set.
     * @return This builder for chaining.
     */
    public Builder setService(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      service_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string service = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearService() {
      service_ = getDefaultInstance().getService();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string service = 1;</code>
     * @param value The bytes for service to set.
     * @return This builder for chaining.
     */
    public Builder setServiceBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      service_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object name_ = "";
    /**
     * <code>string name = 2;</code>
     * @return The name.
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string name = 2;</code>
     * @return The bytes for name.
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string name = 2;</code>
     * @param value The name to set.
     * @return This builder for chaining.
     */
    public Builder setName(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      name_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string name = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearName() {
      name_ = getDefaultInstance().getName();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string name = 2;</code>
     * @param value The bytes for name to set.
     * @return This builder for chaining.
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      name_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private java.lang.Object resource_ = "";
    /**
     * <code>string resource = 3;</code>
     * @return The resource.
     */
    public java.lang.String getResource() {
      java.lang.Object ref = resource_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        resource_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string resource = 3;</code>
     * @return The bytes for resource.
     */
    public com.google.protobuf.ByteString
        getResourceBytes() {
      java.lang.Object ref = resource_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        resource_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string resource = 3;</code>
     * @param value The resource to set.
     * @return This builder for chaining.
     */
    public Builder setResource(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      resource_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>string resource = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearResource() {
      resource_ = getDefaultInstance().getResource();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <code>string resource = 3;</code>
     * @param value The bytes for resource to set.
     * @return This builder for chaining.
     */
    public Builder setResourceBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      resource_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private long traceID_ ;
    /**
     * <code>uint64 traceID = 4;</code>
     * @return The traceID.
     */
    @java.lang.Override
    public long getTraceID() {
      return traceID_;
    }
    /**
     * <code>uint64 traceID = 4;</code>
     * @param value The traceID to set.
     * @return This builder for chaining.
     */
    public Builder setTraceID(long value) {
      
      traceID_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>uint64 traceID = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearTraceID() {
      bitField0_ = (bitField0_ & ~0x00000008);
      traceID_ = 0L;
      onChanged();
      return this;
    }

    private long spanID_ ;
    /**
     * <code>uint64 spanID = 5;</code>
     * @return The spanID.
     */
    @java.lang.Override
    public long getSpanID() {
      return spanID_;
    }
    /**
     * <code>uint64 spanID = 5;</code>
     * @param value The spanID to set.
     * @return This builder for chaining.
     */
    public Builder setSpanID(long value) {
      
      spanID_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>uint64 spanID = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearSpanID() {
      bitField0_ = (bitField0_ & ~0x00000010);
      spanID_ = 0L;
      onChanged();
      return this;
    }

    private long parentID_ ;
    /**
     * <code>uint64 parentID = 6;</code>
     * @return The parentID.
     */
    @java.lang.Override
    public long getParentID() {
      return parentID_;
    }
    /**
     * <code>uint64 parentID = 6;</code>
     * @param value The parentID to set.
     * @return This builder for chaining.
     */
    public Builder setParentID(long value) {
      
      parentID_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>uint64 parentID = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearParentID() {
      bitField0_ = (bitField0_ & ~0x00000020);
      parentID_ = 0L;
      onChanged();
      return this;
    }

    private long start_ ;
    /**
     * <code>int64 start = 7;</code>
     * @return The start.
     */
    @java.lang.Override
    public long getStart() {
      return start_;
    }
    /**
     * <code>int64 start = 7;</code>
     * @param value The start to set.
     * @return This builder for chaining.
     */
    public Builder setStart(long value) {
      
      start_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <code>int64 start = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearStart() {
      bitField0_ = (bitField0_ & ~0x00000040);
      start_ = 0L;
      onChanged();
      return this;
    }

    private long duration_ ;
    /**
     * <code>int64 duration = 8;</code>
     * @return The duration.
     */
    @java.lang.Override
    public long getDuration() {
      return duration_;
    }
    /**
     * <code>int64 duration = 8;</code>
     * @param value The duration to set.
     * @return This builder for chaining.
     */
    public Builder setDuration(long value) {
      
      duration_ = value;
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }
    /**
     * <code>int64 duration = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearDuration() {
      bitField0_ = (bitField0_ & ~0x00000080);
      duration_ = 0L;
      onChanged();
      return this;
    }

    private int error_ ;
    /**
     * <code>int32 error = 9;</code>
     * @return The error.
     */
    @java.lang.Override
    public int getError() {
      return error_;
    }
    /**
     * <code>int32 error = 9;</code>
     * @param value The error to set.
     * @return This builder for chaining.
     */
    public Builder setError(int value) {
      
      error_ = value;
      bitField0_ |= 0x00000100;
      onChanged();
      return this;
    }
    /**
     * <code>int32 error = 9;</code>
     * @return This builder for chaining.
     */
    public Builder clearError() {
      bitField0_ = (bitField0_ & ~0x00000100);
      error_ = 0;
      onChanged();
      return this;
    }

    private com.google.protobuf.MapField<
        java.lang.String, java.lang.String> meta_;
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
        internalGetMeta() {
      if (meta_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            MetaDefaultEntryHolder.defaultEntry);
      }
      return meta_;
    }
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
        internalGetMutableMeta() {
      if (meta_ == null) {
        meta_ = com.google.protobuf.MapField.newMapField(
            MetaDefaultEntryHolder.defaultEntry);
      }
      if (!meta_.isMutable()) {
        meta_ = meta_.copy();
      }
      bitField0_ |= 0x00000200;
      onChanged();
      return meta_;
    }
    public int getMetaCount() {
      return internalGetMeta().getMap().size();
    }
    /**
     * <code>map&lt;string, string&gt; meta = 10;</code>
     */
    @java.lang.Override
    public boolean containsMeta(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      return internalGetMeta().getMap().containsKey(key);
    }
    /**
     * Use {@link #getMetaMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String> getMeta() {
      return getMetaMap();
    }
    /**
     * <code>map&lt;string, string&gt; meta = 10;</code>
     */
    @java.lang.Override
    public java.util.Map<java.lang.String, java.lang.String> getMetaMap() {
      return internalGetMeta().getMap();
    }
    /**
     * <code>map&lt;string, string&gt; meta = 10;</code>
     */
    @java.lang.Override
    public /* nullable */
java.lang.String getMetaOrDefault(
        java.lang.String key,
        /* nullable */
java.lang.String defaultValue) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetMeta().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, string&gt; meta = 10;</code>
     */
    @java.lang.Override
    public java.lang.String getMetaOrThrow(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetMeta().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }
    public Builder clearMeta() {
      bitField0_ = (bitField0_ & ~0x00000200);
      internalGetMutableMeta().getMutableMap()
          .clear();
      return this;
    }
    /**
     * <code>map&lt;string, string&gt; meta = 10;</code>
     */
    public Builder removeMeta(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      internalGetMutableMeta().getMutableMap()
          .remove(key);
      return this;
    }
    /**
     * Use alternate mutation accessors instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String>
        getMutableMeta() {
      bitField0_ |= 0x00000200;
      return internalGetMutableMeta().getMutableMap();
    }
    /**
     * <code>map&lt;string, string&gt; meta = 10;</code>
     */
    public Builder putMeta(
        java.lang.String key,
        java.lang.String value) {
      if (key == null) { throw new NullPointerException("map key"); }
      if (value == null) { throw new NullPointerException("map value"); }
      internalGetMutableMeta().getMutableMap()
          .put(key, value);
      bitField0_ |= 0x00000200;
      return this;
    }
    /**
     * <code>map&lt;string, string&gt; meta = 10;</code>
     */
    public Builder putAllMeta(
        java.util.Map<java.lang.String, java.lang.String> values) {
      internalGetMutableMeta().getMutableMap()
          .putAll(values);
      bitField0_ |= 0x00000200;
      return this;
    }

    private com.google.protobuf.MapField<
        java.lang.String, java.lang.Double> metrics_;
    private com.google.protobuf.MapField<java.lang.String, java.lang.Double>
        internalGetMetrics() {
      if (metrics_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            MetricsDefaultEntryHolder.defaultEntry);
      }
      return metrics_;
    }
    private com.google.protobuf.MapField<java.lang.String, java.lang.Double>
        internalGetMutableMetrics() {
      if (metrics_ == null) {
        metrics_ = com.google.protobuf.MapField.newMapField(
            MetricsDefaultEntryHolder.defaultEntry);
      }
      if (!metrics_.isMutable()) {
        metrics_ = metrics_.copy();
      }
      bitField0_ |= 0x00000400;
      onChanged();
      return metrics_;
    }
    public int getMetricsCount() {
      return internalGetMetrics().getMap().size();
    }
    /**
     * <code>map&lt;string, double&gt; metrics = 11;</code>
     */
    @java.lang.Override
    public boolean containsMetrics(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      return internalGetMetrics().getMap().containsKey(key);
    }
    /**
     * Use {@link #getMetricsMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.Double> getMetrics() {
      return getMetricsMap();
    }
    /**
     * <code>map&lt;string, double&gt; metrics = 11;</code>
     */
    @java.lang.Override
    public java.util.Map<java.lang.String, java.lang.Double> getMetricsMap() {
      return internalGetMetrics().getMap();
    }
    /**
     * <code>map&lt;string, double&gt; metrics = 11;</code>
     */
    @java.lang.Override
    public double getMetricsOrDefault(
        java.lang.String key,
        double defaultValue) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, java.lang.Double> map =
          internalGetMetrics().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, double&gt; metrics = 11;</code>
     */
    @java.lang.Override
    public double getMetricsOrThrow(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, java.lang.Double> map =
          internalGetMetrics().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }
    public Builder clearMetrics() {
      bitField0_ = (bitField0_ & ~0x00000400);
      internalGetMutableMetrics().getMutableMap()
          .clear();
      return this;
    }
    /**
     * <code>map&lt;string, double&gt; metrics = 11;</code>
     */
    public Builder removeMetrics(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      internalGetMutableMetrics().getMutableMap()
          .remove(key);
      return this;
    }
    /**
     * Use alternate mutation accessors instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.Double>
        getMutableMetrics() {
      bitField0_ |= 0x00000400;
      return internalGetMutableMetrics().getMutableMap();
    }
    /**
     * <code>map&lt;string, double&gt; metrics = 11;</code>
     */
    public Builder putMetrics(
        java.lang.String key,
        double value) {
      if (key == null) { throw new NullPointerException("map key"); }
      
      internalGetMutableMetrics().getMutableMap()
          .put(key, value);
      bitField0_ |= 0x00000400;
      return this;
    }
    /**
     * <code>map&lt;string, double&gt; metrics = 11;</code>
     */
    public Builder putAllMetrics(
        java.util.Map<java.lang.String, java.lang.Double> values) {
      internalGetMutableMetrics().getMutableMap()
          .putAll(values);
      bitField0_ |= 0x00000400;
      return this;
    }

    private java.lang.Object type_ = "";
    /**
     * <code>string type = 12;</code>
     * @return The type.
     */
    public java.lang.String getType() {
      java.lang.Object ref = type_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        type_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string type = 12;</code>
     * @return The bytes for type.
     */
    public com.google.protobuf.ByteString
        getTypeBytes() {
      java.lang.Object ref = type_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        type_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string type = 12;</code>
     * @param value The type to set.
     * @return This builder for chaining.
     */
    public Builder setType(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      type_ = value;
      bitField0_ |= 0x00000800;
      onChanged();
      return this;
    }
    /**
     * <code>string type = 12;</code>
     * @return This builder for chaining.
     */
    public Builder clearType() {
      type_ = getDefaultInstance().getType();
      bitField0_ = (bitField0_ & ~0x00000800);
      onChanged();
      return this;
    }
    /**
     * <code>string type = 12;</code>
     * @param value The bytes for type to set.
     * @return This builder for chaining.
     */
    public Builder setTypeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      type_ = value;
      bitField0_ |= 0x00000800;
      onChanged();
      return this;
    }

    private com.google.protobuf.MapField<
        java.lang.String, com.google.protobuf.ByteString> metaStruct_;
    private com.google.protobuf.MapField<java.lang.String, com.google.protobuf.ByteString>
        internalGetMetaStruct() {
      if (metaStruct_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            MetaStructDefaultEntryHolder.defaultEntry);
      }
      return metaStruct_;
    }
    private com.google.protobuf.MapField<java.lang.String, com.google.protobuf.ByteString>
        internalGetMutableMetaStruct() {
      if (metaStruct_ == null) {
        metaStruct_ = com.google.protobuf.MapField.newMapField(
            MetaStructDefaultEntryHolder.defaultEntry);
      }
      if (!metaStruct_.isMutable()) {
        metaStruct_ = metaStruct_.copy();
      }
      bitField0_ |= 0x00001000;
      onChanged();
      return metaStruct_;
    }
    public int getMetaStructCount() {
      return internalGetMetaStruct().getMap().size();
    }
    /**
     * <code>map&lt;string, bytes&gt; meta_struct = 13;</code>
     */
    @java.lang.Override
    public boolean containsMetaStruct(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      return internalGetMetaStruct().getMap().containsKey(key);
    }
    /**
     * Use {@link #getMetaStructMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, com.google.protobuf.ByteString> getMetaStruct() {
      return getMetaStructMap();
    }
    /**
     * <code>map&lt;string, bytes&gt; meta_struct = 13;</code>
     */
    @java.lang.Override
    public java.util.Map<java.lang.String, com.google.protobuf.ByteString> getMetaStructMap() {
      return internalGetMetaStruct().getMap();
    }
    /**
     * <code>map&lt;string, bytes&gt; meta_struct = 13;</code>
     */
    @java.lang.Override
    public /* nullable */
com.google.protobuf.ByteString getMetaStructOrDefault(
        java.lang.String key,
        /* nullable */
com.google.protobuf.ByteString defaultValue) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, com.google.protobuf.ByteString> map =
          internalGetMetaStruct().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, bytes&gt; meta_struct = 13;</code>
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getMetaStructOrThrow(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, com.google.protobuf.ByteString> map =
          internalGetMetaStruct().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }
    public Builder clearMetaStruct() {
      bitField0_ = (bitField0_ & ~0x00001000);
      internalGetMutableMetaStruct().getMutableMap()
          .clear();
      return this;
    }
    /**
     * <code>map&lt;string, bytes&gt; meta_struct = 13;</code>
     */
    public Builder removeMetaStruct(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      internalGetMutableMetaStruct().getMutableMap()
          .remove(key);
      return this;
    }
    /**
     * Use alternate mutation accessors instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, com.google.protobuf.ByteString>
        getMutableMetaStruct() {
      bitField0_ |= 0x00001000;
      return internalGetMutableMetaStruct().getMutableMap();
    }
    /**
     * <code>map&lt;string, bytes&gt; meta_struct = 13;</code>
     */
    public Builder putMetaStruct(
        java.lang.String key,
        com.google.protobuf.ByteString value) {
      if (key == null) { throw new NullPointerException("map key"); }
      if (value == null) { throw new NullPointerException("map value"); }
      internalGetMutableMetaStruct().getMutableMap()
          .put(key, value);
      bitField0_ |= 0x00001000;
      return this;
    }
    /**
     * <code>map&lt;string, bytes&gt; meta_struct = 13;</code>
     */
    public Builder putAllMetaStruct(
        java.util.Map<java.lang.String, com.google.protobuf.ByteString> values) {
      internalGetMutableMetaStruct().getMutableMap()
          .putAll(values);
      bitField0_ |= 0x00001000;
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:pb.APISpan)
  }

  // @@protoc_insertion_point(class_scope:pb.APISpan)
  private static final com.dd.agent.pb.APISpan DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.dd.agent.pb.APISpan();
  }

  public static com.dd.agent.pb.APISpan getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<APISpan>
      PARSER = new com.google.protobuf.AbstractParser<APISpan>() {
    @java.lang.Override
    public APISpan parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<APISpan> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<APISpan> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.dd.agent.pb.APISpan getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

