// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/resources/protos/trace.proto

package com.dd.agent.pb;

public final class APITraceProto {
  private APITraceProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pb_APISpan_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pb_APISpan_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pb_APISpan_MetaEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pb_APISpan_MetaEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pb_APISpan_MetricsEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pb_APISpan_MetricsEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pb_APISpan_MetaStructEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pb_APISpan_MetaStructEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pb_APITraceChunk_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pb_APITraceChunk_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pb_APITraceChunk_TagsEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pb_APITraceChunk_TagsEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pb_APITracerPayload_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pb_APITracerPayload_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pb_APITracerPayload_TagsEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pb_APITracerPayload_TagsEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pb_APITrace_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pb_APITrace_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pb_APITracePayload_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pb_APITracePayload_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pb_APITracePayload_TagsEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pb_APITracePayload_TagsEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n%src/main/resources/protos/trace.proto\022" +
      "\002pb\"\275\003\n\007APISpan\022\017\n\007service\030\001 \001(\t\022\014\n\004name" +
      "\030\002 \001(\t\022\020\n\010resource\030\003 \001(\t\022\017\n\007traceID\030\004 \001(" +
      "\004\022\016\n\006spanID\030\005 \001(\004\022\020\n\010parentID\030\006 \001(\004\022\r\n\005s" +
      "tart\030\007 \001(\003\022\020\n\010duration\030\010 \001(\003\022\r\n\005error\030\t " +
      "\001(\005\022#\n\004meta\030\n \003(\0132\025.pb.APISpan.MetaEntry" +
      "\022)\n\007metrics\030\013 \003(\0132\030.pb.APISpan.MetricsEn" +
      "try\022\014\n\004type\030\014 \001(\t\0220\n\013meta_struct\030\r \003(\0132\033" +
      ".pb.APISpan.MetaStructEntry\032+\n\tMetaEntry" +
      "\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \001(\t:\0028\001\032.\n\014Metr" +
      "icsEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \001(\001:\0028\001" +
      "\0321\n\017MetaStructEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005valu" +
      "e\030\002 \001(\014:\0028\001\"\273\001\n\rAPITraceChunk\022\020\n\010priorit" +
      "y\030\001 \001(\005\022\016\n\006origin\030\002 \001(\t\022\032\n\005spans\030\003 \003(\0132\013" +
      ".pb.APISpan\022)\n\004tags\030\004 \003(\0132\033.pb.APITraceC" +
      "hunk.TagsEntry\022\024\n\014droppedTrace\030\005 \001(\010\032+\n\t" +
      "TagsEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \001(\t:\0028" +
      "\001\"\261\002\n\020APITracerPayload\022\023\n\013containerID\030\001 " +
      "\001(\t\022\024\n\014languageName\030\002 \001(\t\022\027\n\017languageVer" +
      "sion\030\003 \001(\t\022\025\n\rtracerVersion\030\004 \001(\t\022\021\n\trun" +
      "timeID\030\005 \001(\t\022!\n\006chunks\030\006 \003(\0132\021.pb.APITra" +
      "ceChunk\022,\n\004tags\030\007 \003(\0132\036.pb.APITracerPayl" +
      "oad.TagsEntry\022\013\n\003env\030\010 \001(\t\022\020\n\010hostname\030\t" +
      " \001(\t\022\022\n\nappVersion\030\n \001(\t\032+\n\tTagsEntry\022\013\n" +
      "\003key\030\001 \001(\t\022\r\n\005value\030\002 \001(\t:\0028\001\"[\n\010APITrac" +
      "e\022\017\n\007traceID\030\001 \001(\004\022\032\n\005spans\030\002 \003(\0132\013.pb.A" +
      "PISpan\022\021\n\tstartTime\030\006 \001(\003\022\017\n\007endTime\030\007 \001" +
      "(\003\"\217\002\n\017APITracePayload\022\020\n\010hostName\030\001 \001(\t" +
      "\022\013\n\003env\030\002 \001(\t\022\034\n\006traces\030\003 \003(\0132\014.pb.APITr" +
      "ace\022!\n\014transactions\030\004 \003(\0132\013.pb.APISpan\022," +
      "\n\016tracerPayloads\030\005 \003(\0132\024.pb.APITracerPay" +
      "load\022+\n\004tags\030\006 \003(\0132\035.pb.APITracePayload." +
      "TagsEntry\022\024\n\014agentVersion\030\007 \001(\t\032+\n\tTagsE" +
      "ntry\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \001(\t:\0028\001B\"\n\017" +
      "com.dd.agent.pbB\rAPITraceProtoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_pb_APISpan_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_pb_APISpan_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pb_APISpan_descriptor,
        new java.lang.String[] { "Service", "Name", "Resource", "TraceID", "SpanID", "ParentID", "Start", "Duration", "Error", "Meta", "Metrics", "Type", "MetaStruct", });
    internal_static_pb_APISpan_MetaEntry_descriptor =
      internal_static_pb_APISpan_descriptor.getNestedTypes().get(0);
    internal_static_pb_APISpan_MetaEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pb_APISpan_MetaEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_pb_APISpan_MetricsEntry_descriptor =
      internal_static_pb_APISpan_descriptor.getNestedTypes().get(1);
    internal_static_pb_APISpan_MetricsEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pb_APISpan_MetricsEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_pb_APISpan_MetaStructEntry_descriptor =
      internal_static_pb_APISpan_descriptor.getNestedTypes().get(2);
    internal_static_pb_APISpan_MetaStructEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pb_APISpan_MetaStructEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_pb_APITraceChunk_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_pb_APITraceChunk_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pb_APITraceChunk_descriptor,
        new java.lang.String[] { "Priority", "Origin", "Spans", "Tags", "DroppedTrace", });
    internal_static_pb_APITraceChunk_TagsEntry_descriptor =
      internal_static_pb_APITraceChunk_descriptor.getNestedTypes().get(0);
    internal_static_pb_APITraceChunk_TagsEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pb_APITraceChunk_TagsEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_pb_APITracerPayload_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_pb_APITracerPayload_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pb_APITracerPayload_descriptor,
        new java.lang.String[] { "ContainerID", "LanguageName", "LanguageVersion", "TracerVersion", "RuntimeID", "Chunks", "Tags", "Env", "Hostname", "AppVersion", });
    internal_static_pb_APITracerPayload_TagsEntry_descriptor =
      internal_static_pb_APITracerPayload_descriptor.getNestedTypes().get(0);
    internal_static_pb_APITracerPayload_TagsEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pb_APITracerPayload_TagsEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_pb_APITrace_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_pb_APITrace_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pb_APITrace_descriptor,
        new java.lang.String[] { "TraceID", "Spans", "StartTime", "EndTime", });
    internal_static_pb_APITracePayload_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_pb_APITracePayload_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pb_APITracePayload_descriptor,
        new java.lang.String[] { "HostName", "Env", "Traces", "Transactions", "TracerPayloads", "Tags", "AgentVersion", });
    internal_static_pb_APITracePayload_TagsEntry_descriptor =
      internal_static_pb_APITracePayload_descriptor.getNestedTypes().get(0);
    internal_static_pb_APITracePayload_TagsEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pb_APITracePayload_TagsEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
