// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/resources/protos/trace.proto

package com.dd.agent.pb;

public interface APITraceChunkOrBuilder extends
    // @@protoc_insertion_point(interface_extends:pb.APITraceChunk)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 priority = 1;</code>
   * @return The priority.
   */
  int getPriority();

  /**
   * <code>string origin = 2;</code>
   * @return The origin.
   */
  java.lang.String getOrigin();
  /**
   * <code>string origin = 2;</code>
   * @return The bytes for origin.
   */
  com.google.protobuf.ByteString
      getOriginBytes();

  /**
   * <code>repeated .pb.APISpan spans = 3;</code>
   */
  java.util.List<com.dd.agent.pb.APISpan> 
      getSpansList();
  /**
   * <code>repeated .pb.APISpan spans = 3;</code>
   */
  com.dd.agent.pb.APISpan getSpans(int index);
  /**
   * <code>repeated .pb.APISpan spans = 3;</code>
   */
  int getSpansCount();
  /**
   * <code>repeated .pb.APISpan spans = 3;</code>
   */
  java.util.List<? extends com.dd.agent.pb.APISpanOrBuilder> 
      getSpansOrBuilderList();
  /**
   * <code>repeated .pb.APISpan spans = 3;</code>
   */
  com.dd.agent.pb.APISpanOrBuilder getSpansOrBuilder(
      int index);

  /**
   * <code>map&lt;string, string&gt; tags = 4;</code>
   */
  int getTagsCount();
  /**
   * <code>map&lt;string, string&gt; tags = 4;</code>
   */
  boolean containsTags(
      java.lang.String key);
  /**
   * Use {@link #getTagsMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, java.lang.String>
  getTags();
  /**
   * <code>map&lt;string, string&gt; tags = 4;</code>
   */
  java.util.Map<java.lang.String, java.lang.String>
  getTagsMap();
  /**
   * <code>map&lt;string, string&gt; tags = 4;</code>
   */
  /* nullable */
java.lang.String getTagsOrDefault(
      java.lang.String key,
      /* nullable */
java.lang.String defaultValue);
  /**
   * <code>map&lt;string, string&gt; tags = 4;</code>
   */
  java.lang.String getTagsOrThrow(
      java.lang.String key);

  /**
   * <code>bool droppedTrace = 5;</code>
   * @return The droppedTrace.
   */
  boolean getDroppedTrace();
}
