// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/resources/protos/trace.proto

package com.dd.agent.pb;

public interface APITraceOrBuilder extends
    // @@protoc_insertion_point(interface_extends:pb.APITrace)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>uint64 traceID = 1;</code>
   * @return The traceID.
   */
  long getTraceID();

  /**
   * <code>repeated .pb.APISpan spans = 2;</code>
   */
  java.util.List<com.dd.agent.pb.APISpan> 
      getSpansList();
  /**
   * <code>repeated .pb.APISpan spans = 2;</code>
   */
  com.dd.agent.pb.APISpan getSpans(int index);
  /**
   * <code>repeated .pb.APISpan spans = 2;</code>
   */
  int getSpansCount();
  /**
   * <code>repeated .pb.APISpan spans = 2;</code>
   */
  java.util.List<? extends com.dd.agent.pb.APISpanOrBuilder> 
      getSpansOrBuilderList();
  /**
   * <code>repeated .pb.APISpan spans = 2;</code>
   */
  com.dd.agent.pb.APISpanOrBuilder getSpansOrBuilder(
      int index);

  /**
   * <code>int64 startTime = 6;</code>
   * @return The startTime.
   */
  long getStartTime();

  /**
   * <code>int64 endTime = 7;</code>
   * @return The endTime.
   */
  long getEndTime();
}
