// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/resources/protos/trace.proto

package com.dd.agent.pb;

/**
 * Protobuf type {@code pb.APITracePayload}
 */
public final class APITracePayload extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:pb.APITracePayload)
    APITracePayloadOrBuilder {
private static final long serialVersionUID = 0L;
  // Use APITracePayload.newBuilder() to construct.
  private APITracePayload(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private APITracePayload() {
    hostName_ = "";
    env_ = "";
    traces_ = java.util.Collections.emptyList();
    transactions_ = java.util.Collections.emptyList();
    tracerPayloads_ = java.util.Collections.emptyList();
    agentVersion_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new APITracePayload();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.dd.agent.pb.APITraceProto.internal_static_pb_APITracePayload_descriptor;
  }

  @SuppressWarnings({"rawtypes"})
  @java.lang.Override
  protected com.google.protobuf.MapField internalGetMapField(
      int number) {
    switch (number) {
      case 6:
        return internalGetTags();
      default:
        throw new RuntimeException(
            "Invalid map field number: " + number);
    }
  }
  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.dd.agent.pb.APITraceProto.internal_static_pb_APITracePayload_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.dd.agent.pb.APITracePayload.class, com.dd.agent.pb.APITracePayload.Builder.class);
  }

  public static final int HOSTNAME_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object hostName_ = "";
  /**
   * <code>string hostName = 1;</code>
   * @return The hostName.
   */
  @java.lang.Override
  public java.lang.String getHostName() {
    java.lang.Object ref = hostName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      hostName_ = s;
      return s;
    }
  }
  /**
   * <code>string hostName = 1;</code>
   * @return The bytes for hostName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getHostNameBytes() {
    java.lang.Object ref = hostName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      hostName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ENV_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object env_ = "";
  /**
   * <code>string env = 2;</code>
   * @return The env.
   */
  @java.lang.Override
  public java.lang.String getEnv() {
    java.lang.Object ref = env_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      env_ = s;
      return s;
    }
  }
  /**
   * <code>string env = 2;</code>
   * @return The bytes for env.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getEnvBytes() {
    java.lang.Object ref = env_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      env_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TRACES_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private java.util.List<com.dd.agent.pb.APITrace> traces_;
  /**
   * <code>repeated .pb.APITrace traces = 3;</code>
   */
  @java.lang.Override
  public java.util.List<com.dd.agent.pb.APITrace> getTracesList() {
    return traces_;
  }
  /**
   * <code>repeated .pb.APITrace traces = 3;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.dd.agent.pb.APITraceOrBuilder> 
      getTracesOrBuilderList() {
    return traces_;
  }
  /**
   * <code>repeated .pb.APITrace traces = 3;</code>
   */
  @java.lang.Override
  public int getTracesCount() {
    return traces_.size();
  }
  /**
   * <code>repeated .pb.APITrace traces = 3;</code>
   */
  @java.lang.Override
  public com.dd.agent.pb.APITrace getTraces(int index) {
    return traces_.get(index);
  }
  /**
   * <code>repeated .pb.APITrace traces = 3;</code>
   */
  @java.lang.Override
  public com.dd.agent.pb.APITraceOrBuilder getTracesOrBuilder(
      int index) {
    return traces_.get(index);
  }

  public static final int TRANSACTIONS_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private java.util.List<com.dd.agent.pb.APISpan> transactions_;
  /**
   * <code>repeated .pb.APISpan transactions = 4;</code>
   */
  @java.lang.Override
  public java.util.List<com.dd.agent.pb.APISpan> getTransactionsList() {
    return transactions_;
  }
  /**
   * <code>repeated .pb.APISpan transactions = 4;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.dd.agent.pb.APISpanOrBuilder> 
      getTransactionsOrBuilderList() {
    return transactions_;
  }
  /**
   * <code>repeated .pb.APISpan transactions = 4;</code>
   */
  @java.lang.Override
  public int getTransactionsCount() {
    return transactions_.size();
  }
  /**
   * <code>repeated .pb.APISpan transactions = 4;</code>
   */
  @java.lang.Override
  public com.dd.agent.pb.APISpan getTransactions(int index) {
    return transactions_.get(index);
  }
  /**
   * <code>repeated .pb.APISpan transactions = 4;</code>
   */
  @java.lang.Override
  public com.dd.agent.pb.APISpanOrBuilder getTransactionsOrBuilder(
      int index) {
    return transactions_.get(index);
  }

  public static final int TRACERPAYLOADS_FIELD_NUMBER = 5;
  @SuppressWarnings("serial")
  private java.util.List<com.dd.agent.pb.APITracerPayload> tracerPayloads_;
  /**
   * <code>repeated .pb.APITracerPayload tracerPayloads = 5;</code>
   */
  @java.lang.Override
  public java.util.List<com.dd.agent.pb.APITracerPayload> getTracerPayloadsList() {
    return tracerPayloads_;
  }
  /**
   * <code>repeated .pb.APITracerPayload tracerPayloads = 5;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.dd.agent.pb.APITracerPayloadOrBuilder> 
      getTracerPayloadsOrBuilderList() {
    return tracerPayloads_;
  }
  /**
   * <code>repeated .pb.APITracerPayload tracerPayloads = 5;</code>
   */
  @java.lang.Override
  public int getTracerPayloadsCount() {
    return tracerPayloads_.size();
  }
  /**
   * <code>repeated .pb.APITracerPayload tracerPayloads = 5;</code>
   */
  @java.lang.Override
  public com.dd.agent.pb.APITracerPayload getTracerPayloads(int index) {
    return tracerPayloads_.get(index);
  }
  /**
   * <code>repeated .pb.APITracerPayload tracerPayloads = 5;</code>
   */
  @java.lang.Override
  public com.dd.agent.pb.APITracerPayloadOrBuilder getTracerPayloadsOrBuilder(
      int index) {
    return tracerPayloads_.get(index);
  }

  public static final int TAGS_FIELD_NUMBER = 6;
  private static final class TagsDefaultEntryHolder {
    static final com.google.protobuf.MapEntry<
        java.lang.String, java.lang.String> defaultEntry =
            com.google.protobuf.MapEntry
            .<java.lang.String, java.lang.String>newDefaultInstance(
                com.dd.agent.pb.APITraceProto.internal_static_pb_APITracePayload_TagsEntry_descriptor, 
                com.google.protobuf.WireFormat.FieldType.STRING,
                "",
                com.google.protobuf.WireFormat.FieldType.STRING,
                "");
  }
  @SuppressWarnings("serial")
  private com.google.protobuf.MapField<
      java.lang.String, java.lang.String> tags_;
  private com.google.protobuf.MapField<java.lang.String, java.lang.String>
  internalGetTags() {
    if (tags_ == null) {
      return com.google.protobuf.MapField.emptyMapField(
          TagsDefaultEntryHolder.defaultEntry);
    }
    return tags_;
  }
  public int getTagsCount() {
    return internalGetTags().getMap().size();
  }
  /**
   * <code>map&lt;string, string&gt; tags = 6;</code>
   */
  @java.lang.Override
  public boolean containsTags(
      java.lang.String key) {
    if (key == null) { throw new NullPointerException("map key"); }
    return internalGetTags().getMap().containsKey(key);
  }
  /**
   * Use {@link #getTagsMap()} instead.
   */
  @java.lang.Override
  @java.lang.Deprecated
  public java.util.Map<java.lang.String, java.lang.String> getTags() {
    return getTagsMap();
  }
  /**
   * <code>map&lt;string, string&gt; tags = 6;</code>
   */
  @java.lang.Override
  public java.util.Map<java.lang.String, java.lang.String> getTagsMap() {
    return internalGetTags().getMap();
  }
  /**
   * <code>map&lt;string, string&gt; tags = 6;</code>
   */
  @java.lang.Override
  public /* nullable */
java.lang.String getTagsOrDefault(
      java.lang.String key,
      /* nullable */
java.lang.String defaultValue) {
    if (key == null) { throw new NullPointerException("map key"); }
    java.util.Map<java.lang.String, java.lang.String> map =
        internalGetTags().getMap();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }
  /**
   * <code>map&lt;string, string&gt; tags = 6;</code>
   */
  @java.lang.Override
  public java.lang.String getTagsOrThrow(
      java.lang.String key) {
    if (key == null) { throw new NullPointerException("map key"); }
    java.util.Map<java.lang.String, java.lang.String> map =
        internalGetTags().getMap();
    if (!map.containsKey(key)) {
      throw new java.lang.IllegalArgumentException();
    }
    return map.get(key);
  }

  public static final int AGENTVERSION_FIELD_NUMBER = 7;
  @SuppressWarnings("serial")
  private volatile java.lang.Object agentVersion_ = "";
  /**
   * <code>string agentVersion = 7;</code>
   * @return The agentVersion.
   */
  @java.lang.Override
  public java.lang.String getAgentVersion() {
    java.lang.Object ref = agentVersion_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      agentVersion_ = s;
      return s;
    }
  }
  /**
   * <code>string agentVersion = 7;</code>
   * @return The bytes for agentVersion.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getAgentVersionBytes() {
    java.lang.Object ref = agentVersion_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      agentVersion_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(hostName_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, hostName_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(env_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, env_);
    }
    for (int i = 0; i < traces_.size(); i++) {
      output.writeMessage(3, traces_.get(i));
    }
    for (int i = 0; i < transactions_.size(); i++) {
      output.writeMessage(4, transactions_.get(i));
    }
    for (int i = 0; i < tracerPayloads_.size(); i++) {
      output.writeMessage(5, tracerPayloads_.get(i));
    }
    com.google.protobuf.GeneratedMessageV3
      .serializeStringMapTo(
        output,
        internalGetTags(),
        TagsDefaultEntryHolder.defaultEntry,
        6);
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(agentVersion_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 7, agentVersion_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(hostName_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, hostName_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(env_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, env_);
    }
    for (int i = 0; i < traces_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, traces_.get(i));
    }
    for (int i = 0; i < transactions_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, transactions_.get(i));
    }
    for (int i = 0; i < tracerPayloads_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, tracerPayloads_.get(i));
    }
    for (java.util.Map.Entry<java.lang.String, java.lang.String> entry
         : internalGetTags().getMap().entrySet()) {
      com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
      tags__ = TagsDefaultEntryHolder.defaultEntry.newBuilderForType()
          .setKey(entry.getKey())
          .setValue(entry.getValue())
          .build();
      size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(6, tags__);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(agentVersion_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, agentVersion_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.dd.agent.pb.APITracePayload)) {
      return super.equals(obj);
    }
    com.dd.agent.pb.APITracePayload other = (com.dd.agent.pb.APITracePayload) obj;

    if (!getHostName()
        .equals(other.getHostName())) return false;
    if (!getEnv()
        .equals(other.getEnv())) return false;
    if (!getTracesList()
        .equals(other.getTracesList())) return false;
    if (!getTransactionsList()
        .equals(other.getTransactionsList())) return false;
    if (!getTracerPayloadsList()
        .equals(other.getTracerPayloadsList())) return false;
    if (!internalGetTags().equals(
        other.internalGetTags())) return false;
    if (!getAgentVersion()
        .equals(other.getAgentVersion())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + HOSTNAME_FIELD_NUMBER;
    hash = (53 * hash) + getHostName().hashCode();
    hash = (37 * hash) + ENV_FIELD_NUMBER;
    hash = (53 * hash) + getEnv().hashCode();
    if (getTracesCount() > 0) {
      hash = (37 * hash) + TRACES_FIELD_NUMBER;
      hash = (53 * hash) + getTracesList().hashCode();
    }
    if (getTransactionsCount() > 0) {
      hash = (37 * hash) + TRANSACTIONS_FIELD_NUMBER;
      hash = (53 * hash) + getTransactionsList().hashCode();
    }
    if (getTracerPayloadsCount() > 0) {
      hash = (37 * hash) + TRACERPAYLOADS_FIELD_NUMBER;
      hash = (53 * hash) + getTracerPayloadsList().hashCode();
    }
    if (!internalGetTags().getMap().isEmpty()) {
      hash = (37 * hash) + TAGS_FIELD_NUMBER;
      hash = (53 * hash) + internalGetTags().hashCode();
    }
    hash = (37 * hash) + AGENTVERSION_FIELD_NUMBER;
    hash = (53 * hash) + getAgentVersion().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.dd.agent.pb.APITracePayload parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.dd.agent.pb.APITracePayload parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.dd.agent.pb.APITracePayload parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.dd.agent.pb.APITracePayload parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.dd.agent.pb.APITracePayload parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.dd.agent.pb.APITracePayload parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.dd.agent.pb.APITracePayload parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.dd.agent.pb.APITracePayload parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.dd.agent.pb.APITracePayload parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.dd.agent.pb.APITracePayload parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.dd.agent.pb.APITracePayload parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.dd.agent.pb.APITracePayload parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.dd.agent.pb.APITracePayload prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code pb.APITracePayload}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:pb.APITracePayload)
      com.dd.agent.pb.APITracePayloadOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.dd.agent.pb.APITraceProto.internal_static_pb_APITracePayload_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 6:
          return internalGetTags();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMutableMapField(
        int number) {
      switch (number) {
        case 6:
          return internalGetMutableTags();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.dd.agent.pb.APITraceProto.internal_static_pb_APITracePayload_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.dd.agent.pb.APITracePayload.class, com.dd.agent.pb.APITracePayload.Builder.class);
    }

    // Construct using com.dd.agent.pb.APITracePayload.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      hostName_ = "";
      env_ = "";
      if (tracesBuilder_ == null) {
        traces_ = java.util.Collections.emptyList();
      } else {
        traces_ = null;
        tracesBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000004);
      if (transactionsBuilder_ == null) {
        transactions_ = java.util.Collections.emptyList();
      } else {
        transactions_ = null;
        transactionsBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000008);
      if (tracerPayloadsBuilder_ == null) {
        tracerPayloads_ = java.util.Collections.emptyList();
      } else {
        tracerPayloads_ = null;
        tracerPayloadsBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000010);
      internalGetMutableTags().clear();
      agentVersion_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.dd.agent.pb.APITraceProto.internal_static_pb_APITracePayload_descriptor;
    }

    @java.lang.Override
    public com.dd.agent.pb.APITracePayload getDefaultInstanceForType() {
      return com.dd.agent.pb.APITracePayload.getDefaultInstance();
    }

    @java.lang.Override
    public com.dd.agent.pb.APITracePayload build() {
      com.dd.agent.pb.APITracePayload result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.dd.agent.pb.APITracePayload buildPartial() {
      com.dd.agent.pb.APITracePayload result = new com.dd.agent.pb.APITracePayload(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(com.dd.agent.pb.APITracePayload result) {
      if (tracesBuilder_ == null) {
        if (((bitField0_ & 0x00000004) != 0)) {
          traces_ = java.util.Collections.unmodifiableList(traces_);
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.traces_ = traces_;
      } else {
        result.traces_ = tracesBuilder_.build();
      }
      if (transactionsBuilder_ == null) {
        if (((bitField0_ & 0x00000008) != 0)) {
          transactions_ = java.util.Collections.unmodifiableList(transactions_);
          bitField0_ = (bitField0_ & ~0x00000008);
        }
        result.transactions_ = transactions_;
      } else {
        result.transactions_ = transactionsBuilder_.build();
      }
      if (tracerPayloadsBuilder_ == null) {
        if (((bitField0_ & 0x00000010) != 0)) {
          tracerPayloads_ = java.util.Collections.unmodifiableList(tracerPayloads_);
          bitField0_ = (bitField0_ & ~0x00000010);
        }
        result.tracerPayloads_ = tracerPayloads_;
      } else {
        result.tracerPayloads_ = tracerPayloadsBuilder_.build();
      }
    }

    private void buildPartial0(com.dd.agent.pb.APITracePayload result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.hostName_ = hostName_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.env_ = env_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.tags_ = internalGetTags();
        result.tags_.makeImmutable();
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.agentVersion_ = agentVersion_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.dd.agent.pb.APITracePayload) {
        return mergeFrom((com.dd.agent.pb.APITracePayload)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.dd.agent.pb.APITracePayload other) {
      if (other == com.dd.agent.pb.APITracePayload.getDefaultInstance()) return this;
      if (!other.getHostName().isEmpty()) {
        hostName_ = other.hostName_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.getEnv().isEmpty()) {
        env_ = other.env_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (tracesBuilder_ == null) {
        if (!other.traces_.isEmpty()) {
          if (traces_.isEmpty()) {
            traces_ = other.traces_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureTracesIsMutable();
            traces_.addAll(other.traces_);
          }
          onChanged();
        }
      } else {
        if (!other.traces_.isEmpty()) {
          if (tracesBuilder_.isEmpty()) {
            tracesBuilder_.dispose();
            tracesBuilder_ = null;
            traces_ = other.traces_;
            bitField0_ = (bitField0_ & ~0x00000004);
            tracesBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getTracesFieldBuilder() : null;
          } else {
            tracesBuilder_.addAllMessages(other.traces_);
          }
        }
      }
      if (transactionsBuilder_ == null) {
        if (!other.transactions_.isEmpty()) {
          if (transactions_.isEmpty()) {
            transactions_ = other.transactions_;
            bitField0_ = (bitField0_ & ~0x00000008);
          } else {
            ensureTransactionsIsMutable();
            transactions_.addAll(other.transactions_);
          }
          onChanged();
        }
      } else {
        if (!other.transactions_.isEmpty()) {
          if (transactionsBuilder_.isEmpty()) {
            transactionsBuilder_.dispose();
            transactionsBuilder_ = null;
            transactions_ = other.transactions_;
            bitField0_ = (bitField0_ & ~0x00000008);
            transactionsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getTransactionsFieldBuilder() : null;
          } else {
            transactionsBuilder_.addAllMessages(other.transactions_);
          }
        }
      }
      if (tracerPayloadsBuilder_ == null) {
        if (!other.tracerPayloads_.isEmpty()) {
          if (tracerPayloads_.isEmpty()) {
            tracerPayloads_ = other.tracerPayloads_;
            bitField0_ = (bitField0_ & ~0x00000010);
          } else {
            ensureTracerPayloadsIsMutable();
            tracerPayloads_.addAll(other.tracerPayloads_);
          }
          onChanged();
        }
      } else {
        if (!other.tracerPayloads_.isEmpty()) {
          if (tracerPayloadsBuilder_.isEmpty()) {
            tracerPayloadsBuilder_.dispose();
            tracerPayloadsBuilder_ = null;
            tracerPayloads_ = other.tracerPayloads_;
            bitField0_ = (bitField0_ & ~0x00000010);
            tracerPayloadsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getTracerPayloadsFieldBuilder() : null;
          } else {
            tracerPayloadsBuilder_.addAllMessages(other.tracerPayloads_);
          }
        }
      }
      internalGetMutableTags().mergeFrom(
          other.internalGetTags());
      bitField0_ |= 0x00000020;
      if (!other.getAgentVersion().isEmpty()) {
        agentVersion_ = other.agentVersion_;
        bitField0_ |= 0x00000040;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              hostName_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              env_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              com.dd.agent.pb.APITrace m =
                  input.readMessage(
                      com.dd.agent.pb.APITrace.parser(),
                      extensionRegistry);
              if (tracesBuilder_ == null) {
                ensureTracesIsMutable();
                traces_.add(m);
              } else {
                tracesBuilder_.addMessage(m);
              }
              break;
            } // case 26
            case 34: {
              com.dd.agent.pb.APISpan m =
                  input.readMessage(
                      com.dd.agent.pb.APISpan.parser(),
                      extensionRegistry);
              if (transactionsBuilder_ == null) {
                ensureTransactionsIsMutable();
                transactions_.add(m);
              } else {
                transactionsBuilder_.addMessage(m);
              }
              break;
            } // case 34
            case 42: {
              com.dd.agent.pb.APITracerPayload m =
                  input.readMessage(
                      com.dd.agent.pb.APITracerPayload.parser(),
                      extensionRegistry);
              if (tracerPayloadsBuilder_ == null) {
                ensureTracerPayloadsIsMutable();
                tracerPayloads_.add(m);
              } else {
                tracerPayloadsBuilder_.addMessage(m);
              }
              break;
            } // case 42
            case 50: {
              com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
              tags__ = input.readMessage(
                  TagsDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              internalGetMutableTags().getMutableMap().put(
                  tags__.getKey(), tags__.getValue());
              bitField0_ |= 0x00000020;
              break;
            } // case 50
            case 58: {
              agentVersion_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000040;
              break;
            } // case 58
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object hostName_ = "";
    /**
     * <code>string hostName = 1;</code>
     * @return The hostName.
     */
    public java.lang.String getHostName() {
      java.lang.Object ref = hostName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        hostName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string hostName = 1;</code>
     * @return The bytes for hostName.
     */
    public com.google.protobuf.ByteString
        getHostNameBytes() {
      java.lang.Object ref = hostName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        hostName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string hostName = 1;</code>
     * @param value The hostName to set.
     * @return This builder for chaining.
     */
    public Builder setHostName(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      hostName_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string hostName = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearHostName() {
      hostName_ = getDefaultInstance().getHostName();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string hostName = 1;</code>
     * @param value The bytes for hostName to set.
     * @return This builder for chaining.
     */
    public Builder setHostNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      hostName_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object env_ = "";
    /**
     * <code>string env = 2;</code>
     * @return The env.
     */
    public java.lang.String getEnv() {
      java.lang.Object ref = env_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        env_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string env = 2;</code>
     * @return The bytes for env.
     */
    public com.google.protobuf.ByteString
        getEnvBytes() {
      java.lang.Object ref = env_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        env_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string env = 2;</code>
     * @param value The env to set.
     * @return This builder for chaining.
     */
    public Builder setEnv(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      env_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string env = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearEnv() {
      env_ = getDefaultInstance().getEnv();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string env = 2;</code>
     * @param value The bytes for env to set.
     * @return This builder for chaining.
     */
    public Builder setEnvBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      env_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private java.util.List<com.dd.agent.pb.APITrace> traces_ =
      java.util.Collections.emptyList();
    private void ensureTracesIsMutable() {
      if (!((bitField0_ & 0x00000004) != 0)) {
        traces_ = new java.util.ArrayList<com.dd.agent.pb.APITrace>(traces_);
        bitField0_ |= 0x00000004;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.dd.agent.pb.APITrace, com.dd.agent.pb.APITrace.Builder, com.dd.agent.pb.APITraceOrBuilder> tracesBuilder_;

    /**
     * <code>repeated .pb.APITrace traces = 3;</code>
     */
    public java.util.List<com.dd.agent.pb.APITrace> getTracesList() {
      if (tracesBuilder_ == null) {
        return java.util.Collections.unmodifiableList(traces_);
      } else {
        return tracesBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .pb.APITrace traces = 3;</code>
     */
    public int getTracesCount() {
      if (tracesBuilder_ == null) {
        return traces_.size();
      } else {
        return tracesBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .pb.APITrace traces = 3;</code>
     */
    public com.dd.agent.pb.APITrace getTraces(int index) {
      if (tracesBuilder_ == null) {
        return traces_.get(index);
      } else {
        return tracesBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .pb.APITrace traces = 3;</code>
     */
    public Builder setTraces(
        int index, com.dd.agent.pb.APITrace value) {
      if (tracesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTracesIsMutable();
        traces_.set(index, value);
        onChanged();
      } else {
        tracesBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .pb.APITrace traces = 3;</code>
     */
    public Builder setTraces(
        int index, com.dd.agent.pb.APITrace.Builder builderForValue) {
      if (tracesBuilder_ == null) {
        ensureTracesIsMutable();
        traces_.set(index, builderForValue.build());
        onChanged();
      } else {
        tracesBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .pb.APITrace traces = 3;</code>
     */
    public Builder addTraces(com.dd.agent.pb.APITrace value) {
      if (tracesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTracesIsMutable();
        traces_.add(value);
        onChanged();
      } else {
        tracesBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .pb.APITrace traces = 3;</code>
     */
    public Builder addTraces(
        int index, com.dd.agent.pb.APITrace value) {
      if (tracesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTracesIsMutable();
        traces_.add(index, value);
        onChanged();
      } else {
        tracesBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .pb.APITrace traces = 3;</code>
     */
    public Builder addTraces(
        com.dd.agent.pb.APITrace.Builder builderForValue) {
      if (tracesBuilder_ == null) {
        ensureTracesIsMutable();
        traces_.add(builderForValue.build());
        onChanged();
      } else {
        tracesBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .pb.APITrace traces = 3;</code>
     */
    public Builder addTraces(
        int index, com.dd.agent.pb.APITrace.Builder builderForValue) {
      if (tracesBuilder_ == null) {
        ensureTracesIsMutable();
        traces_.add(index, builderForValue.build());
        onChanged();
      } else {
        tracesBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .pb.APITrace traces = 3;</code>
     */
    public Builder addAllTraces(
        java.lang.Iterable<? extends com.dd.agent.pb.APITrace> values) {
      if (tracesBuilder_ == null) {
        ensureTracesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, traces_);
        onChanged();
      } else {
        tracesBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .pb.APITrace traces = 3;</code>
     */
    public Builder clearTraces() {
      if (tracesBuilder_ == null) {
        traces_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
      } else {
        tracesBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .pb.APITrace traces = 3;</code>
     */
    public Builder removeTraces(int index) {
      if (tracesBuilder_ == null) {
        ensureTracesIsMutable();
        traces_.remove(index);
        onChanged();
      } else {
        tracesBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .pb.APITrace traces = 3;</code>
     */
    public com.dd.agent.pb.APITrace.Builder getTracesBuilder(
        int index) {
      return getTracesFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .pb.APITrace traces = 3;</code>
     */
    public com.dd.agent.pb.APITraceOrBuilder getTracesOrBuilder(
        int index) {
      if (tracesBuilder_ == null) {
        return traces_.get(index);  } else {
        return tracesBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .pb.APITrace traces = 3;</code>
     */
    public java.util.List<? extends com.dd.agent.pb.APITraceOrBuilder> 
         getTracesOrBuilderList() {
      if (tracesBuilder_ != null) {
        return tracesBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(traces_);
      }
    }
    /**
     * <code>repeated .pb.APITrace traces = 3;</code>
     */
    public com.dd.agent.pb.APITrace.Builder addTracesBuilder() {
      return getTracesFieldBuilder().addBuilder(
          com.dd.agent.pb.APITrace.getDefaultInstance());
    }
    /**
     * <code>repeated .pb.APITrace traces = 3;</code>
     */
    public com.dd.agent.pb.APITrace.Builder addTracesBuilder(
        int index) {
      return getTracesFieldBuilder().addBuilder(
          index, com.dd.agent.pb.APITrace.getDefaultInstance());
    }
    /**
     * <code>repeated .pb.APITrace traces = 3;</code>
     */
    public java.util.List<com.dd.agent.pb.APITrace.Builder> 
         getTracesBuilderList() {
      return getTracesFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.dd.agent.pb.APITrace, com.dd.agent.pb.APITrace.Builder, com.dd.agent.pb.APITraceOrBuilder> 
        getTracesFieldBuilder() {
      if (tracesBuilder_ == null) {
        tracesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.dd.agent.pb.APITrace, com.dd.agent.pb.APITrace.Builder, com.dd.agent.pb.APITraceOrBuilder>(
                traces_,
                ((bitField0_ & 0x00000004) != 0),
                getParentForChildren(),
                isClean());
        traces_ = null;
      }
      return tracesBuilder_;
    }

    private java.util.List<com.dd.agent.pb.APISpan> transactions_ =
      java.util.Collections.emptyList();
    private void ensureTransactionsIsMutable() {
      if (!((bitField0_ & 0x00000008) != 0)) {
        transactions_ = new java.util.ArrayList<com.dd.agent.pb.APISpan>(transactions_);
        bitField0_ |= 0x00000008;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.dd.agent.pb.APISpan, com.dd.agent.pb.APISpan.Builder, com.dd.agent.pb.APISpanOrBuilder> transactionsBuilder_;

    /**
     * <code>repeated .pb.APISpan transactions = 4;</code>
     */
    public java.util.List<com.dd.agent.pb.APISpan> getTransactionsList() {
      if (transactionsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(transactions_);
      } else {
        return transactionsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .pb.APISpan transactions = 4;</code>
     */
    public int getTransactionsCount() {
      if (transactionsBuilder_ == null) {
        return transactions_.size();
      } else {
        return transactionsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .pb.APISpan transactions = 4;</code>
     */
    public com.dd.agent.pb.APISpan getTransactions(int index) {
      if (transactionsBuilder_ == null) {
        return transactions_.get(index);
      } else {
        return transactionsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .pb.APISpan transactions = 4;</code>
     */
    public Builder setTransactions(
        int index, com.dd.agent.pb.APISpan value) {
      if (transactionsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTransactionsIsMutable();
        transactions_.set(index, value);
        onChanged();
      } else {
        transactionsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .pb.APISpan transactions = 4;</code>
     */
    public Builder setTransactions(
        int index, com.dd.agent.pb.APISpan.Builder builderForValue) {
      if (transactionsBuilder_ == null) {
        ensureTransactionsIsMutable();
        transactions_.set(index, builderForValue.build());
        onChanged();
      } else {
        transactionsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .pb.APISpan transactions = 4;</code>
     */
    public Builder addTransactions(com.dd.agent.pb.APISpan value) {
      if (transactionsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTransactionsIsMutable();
        transactions_.add(value);
        onChanged();
      } else {
        transactionsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .pb.APISpan transactions = 4;</code>
     */
    public Builder addTransactions(
        int index, com.dd.agent.pb.APISpan value) {
      if (transactionsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTransactionsIsMutable();
        transactions_.add(index, value);
        onChanged();
      } else {
        transactionsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .pb.APISpan transactions = 4;</code>
     */
    public Builder addTransactions(
        com.dd.agent.pb.APISpan.Builder builderForValue) {
      if (transactionsBuilder_ == null) {
        ensureTransactionsIsMutable();
        transactions_.add(builderForValue.build());
        onChanged();
      } else {
        transactionsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .pb.APISpan transactions = 4;</code>
     */
    public Builder addTransactions(
        int index, com.dd.agent.pb.APISpan.Builder builderForValue) {
      if (transactionsBuilder_ == null) {
        ensureTransactionsIsMutable();
        transactions_.add(index, builderForValue.build());
        onChanged();
      } else {
        transactionsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .pb.APISpan transactions = 4;</code>
     */
    public Builder addAllTransactions(
        java.lang.Iterable<? extends com.dd.agent.pb.APISpan> values) {
      if (transactionsBuilder_ == null) {
        ensureTransactionsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, transactions_);
        onChanged();
      } else {
        transactionsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .pb.APISpan transactions = 4;</code>
     */
    public Builder clearTransactions() {
      if (transactionsBuilder_ == null) {
        transactions_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
      } else {
        transactionsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .pb.APISpan transactions = 4;</code>
     */
    public Builder removeTransactions(int index) {
      if (transactionsBuilder_ == null) {
        ensureTransactionsIsMutable();
        transactions_.remove(index);
        onChanged();
      } else {
        transactionsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .pb.APISpan transactions = 4;</code>
     */
    public com.dd.agent.pb.APISpan.Builder getTransactionsBuilder(
        int index) {
      return getTransactionsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .pb.APISpan transactions = 4;</code>
     */
    public com.dd.agent.pb.APISpanOrBuilder getTransactionsOrBuilder(
        int index) {
      if (transactionsBuilder_ == null) {
        return transactions_.get(index);  } else {
        return transactionsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .pb.APISpan transactions = 4;</code>
     */
    public java.util.List<? extends com.dd.agent.pb.APISpanOrBuilder> 
         getTransactionsOrBuilderList() {
      if (transactionsBuilder_ != null) {
        return transactionsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(transactions_);
      }
    }
    /**
     * <code>repeated .pb.APISpan transactions = 4;</code>
     */
    public com.dd.agent.pb.APISpan.Builder addTransactionsBuilder() {
      return getTransactionsFieldBuilder().addBuilder(
          com.dd.agent.pb.APISpan.getDefaultInstance());
    }
    /**
     * <code>repeated .pb.APISpan transactions = 4;</code>
     */
    public com.dd.agent.pb.APISpan.Builder addTransactionsBuilder(
        int index) {
      return getTransactionsFieldBuilder().addBuilder(
          index, com.dd.agent.pb.APISpan.getDefaultInstance());
    }
    /**
     * <code>repeated .pb.APISpan transactions = 4;</code>
     */
    public java.util.List<com.dd.agent.pb.APISpan.Builder> 
         getTransactionsBuilderList() {
      return getTransactionsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.dd.agent.pb.APISpan, com.dd.agent.pb.APISpan.Builder, com.dd.agent.pb.APISpanOrBuilder> 
        getTransactionsFieldBuilder() {
      if (transactionsBuilder_ == null) {
        transactionsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.dd.agent.pb.APISpan, com.dd.agent.pb.APISpan.Builder, com.dd.agent.pb.APISpanOrBuilder>(
                transactions_,
                ((bitField0_ & 0x00000008) != 0),
                getParentForChildren(),
                isClean());
        transactions_ = null;
      }
      return transactionsBuilder_;
    }

    private java.util.List<com.dd.agent.pb.APITracerPayload> tracerPayloads_ =
      java.util.Collections.emptyList();
    private void ensureTracerPayloadsIsMutable() {
      if (!((bitField0_ & 0x00000010) != 0)) {
        tracerPayloads_ = new java.util.ArrayList<com.dd.agent.pb.APITracerPayload>(tracerPayloads_);
        bitField0_ |= 0x00000010;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.dd.agent.pb.APITracerPayload, com.dd.agent.pb.APITracerPayload.Builder, com.dd.agent.pb.APITracerPayloadOrBuilder> tracerPayloadsBuilder_;

    /**
     * <code>repeated .pb.APITracerPayload tracerPayloads = 5;</code>
     */
    public java.util.List<com.dd.agent.pb.APITracerPayload> getTracerPayloadsList() {
      if (tracerPayloadsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(tracerPayloads_);
      } else {
        return tracerPayloadsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .pb.APITracerPayload tracerPayloads = 5;</code>
     */
    public int getTracerPayloadsCount() {
      if (tracerPayloadsBuilder_ == null) {
        return tracerPayloads_.size();
      } else {
        return tracerPayloadsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .pb.APITracerPayload tracerPayloads = 5;</code>
     */
    public com.dd.agent.pb.APITracerPayload getTracerPayloads(int index) {
      if (tracerPayloadsBuilder_ == null) {
        return tracerPayloads_.get(index);
      } else {
        return tracerPayloadsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .pb.APITracerPayload tracerPayloads = 5;</code>
     */
    public Builder setTracerPayloads(
        int index, com.dd.agent.pb.APITracerPayload value) {
      if (tracerPayloadsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTracerPayloadsIsMutable();
        tracerPayloads_.set(index, value);
        onChanged();
      } else {
        tracerPayloadsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .pb.APITracerPayload tracerPayloads = 5;</code>
     */
    public Builder setTracerPayloads(
        int index, com.dd.agent.pb.APITracerPayload.Builder builderForValue) {
      if (tracerPayloadsBuilder_ == null) {
        ensureTracerPayloadsIsMutable();
        tracerPayloads_.set(index, builderForValue.build());
        onChanged();
      } else {
        tracerPayloadsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .pb.APITracerPayload tracerPayloads = 5;</code>
     */
    public Builder addTracerPayloads(com.dd.agent.pb.APITracerPayload value) {
      if (tracerPayloadsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTracerPayloadsIsMutable();
        tracerPayloads_.add(value);
        onChanged();
      } else {
        tracerPayloadsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .pb.APITracerPayload tracerPayloads = 5;</code>
     */
    public Builder addTracerPayloads(
        int index, com.dd.agent.pb.APITracerPayload value) {
      if (tracerPayloadsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTracerPayloadsIsMutable();
        tracerPayloads_.add(index, value);
        onChanged();
      } else {
        tracerPayloadsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .pb.APITracerPayload tracerPayloads = 5;</code>
     */
    public Builder addTracerPayloads(
        com.dd.agent.pb.APITracerPayload.Builder builderForValue) {
      if (tracerPayloadsBuilder_ == null) {
        ensureTracerPayloadsIsMutable();
        tracerPayloads_.add(builderForValue.build());
        onChanged();
      } else {
        tracerPayloadsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .pb.APITracerPayload tracerPayloads = 5;</code>
     */
    public Builder addTracerPayloads(
        int index, com.dd.agent.pb.APITracerPayload.Builder builderForValue) {
      if (tracerPayloadsBuilder_ == null) {
        ensureTracerPayloadsIsMutable();
        tracerPayloads_.add(index, builderForValue.build());
        onChanged();
      } else {
        tracerPayloadsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .pb.APITracerPayload tracerPayloads = 5;</code>
     */
    public Builder addAllTracerPayloads(
        java.lang.Iterable<? extends com.dd.agent.pb.APITracerPayload> values) {
      if (tracerPayloadsBuilder_ == null) {
        ensureTracerPayloadsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, tracerPayloads_);
        onChanged();
      } else {
        tracerPayloadsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .pb.APITracerPayload tracerPayloads = 5;</code>
     */
    public Builder clearTracerPayloads() {
      if (tracerPayloadsBuilder_ == null) {
        tracerPayloads_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000010);
        onChanged();
      } else {
        tracerPayloadsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .pb.APITracerPayload tracerPayloads = 5;</code>
     */
    public Builder removeTracerPayloads(int index) {
      if (tracerPayloadsBuilder_ == null) {
        ensureTracerPayloadsIsMutable();
        tracerPayloads_.remove(index);
        onChanged();
      } else {
        tracerPayloadsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .pb.APITracerPayload tracerPayloads = 5;</code>
     */
    public com.dd.agent.pb.APITracerPayload.Builder getTracerPayloadsBuilder(
        int index) {
      return getTracerPayloadsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .pb.APITracerPayload tracerPayloads = 5;</code>
     */
    public com.dd.agent.pb.APITracerPayloadOrBuilder getTracerPayloadsOrBuilder(
        int index) {
      if (tracerPayloadsBuilder_ == null) {
        return tracerPayloads_.get(index);  } else {
        return tracerPayloadsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .pb.APITracerPayload tracerPayloads = 5;</code>
     */
    public java.util.List<? extends com.dd.agent.pb.APITracerPayloadOrBuilder> 
         getTracerPayloadsOrBuilderList() {
      if (tracerPayloadsBuilder_ != null) {
        return tracerPayloadsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(tracerPayloads_);
      }
    }
    /**
     * <code>repeated .pb.APITracerPayload tracerPayloads = 5;</code>
     */
    public com.dd.agent.pb.APITracerPayload.Builder addTracerPayloadsBuilder() {
      return getTracerPayloadsFieldBuilder().addBuilder(
          com.dd.agent.pb.APITracerPayload.getDefaultInstance());
    }
    /**
     * <code>repeated .pb.APITracerPayload tracerPayloads = 5;</code>
     */
    public com.dd.agent.pb.APITracerPayload.Builder addTracerPayloadsBuilder(
        int index) {
      return getTracerPayloadsFieldBuilder().addBuilder(
          index, com.dd.agent.pb.APITracerPayload.getDefaultInstance());
    }
    /**
     * <code>repeated .pb.APITracerPayload tracerPayloads = 5;</code>
     */
    public java.util.List<com.dd.agent.pb.APITracerPayload.Builder> 
         getTracerPayloadsBuilderList() {
      return getTracerPayloadsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.dd.agent.pb.APITracerPayload, com.dd.agent.pb.APITracerPayload.Builder, com.dd.agent.pb.APITracerPayloadOrBuilder> 
        getTracerPayloadsFieldBuilder() {
      if (tracerPayloadsBuilder_ == null) {
        tracerPayloadsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.dd.agent.pb.APITracerPayload, com.dd.agent.pb.APITracerPayload.Builder, com.dd.agent.pb.APITracerPayloadOrBuilder>(
                tracerPayloads_,
                ((bitField0_ & 0x00000010) != 0),
                getParentForChildren(),
                isClean());
        tracerPayloads_ = null;
      }
      return tracerPayloadsBuilder_;
    }

    private com.google.protobuf.MapField<
        java.lang.String, java.lang.String> tags_;
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
        internalGetTags() {
      if (tags_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            TagsDefaultEntryHolder.defaultEntry);
      }
      return tags_;
    }
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
        internalGetMutableTags() {
      if (tags_ == null) {
        tags_ = com.google.protobuf.MapField.newMapField(
            TagsDefaultEntryHolder.defaultEntry);
      }
      if (!tags_.isMutable()) {
        tags_ = tags_.copy();
      }
      bitField0_ |= 0x00000020;
      onChanged();
      return tags_;
    }
    public int getTagsCount() {
      return internalGetTags().getMap().size();
    }
    /**
     * <code>map&lt;string, string&gt; tags = 6;</code>
     */
    @java.lang.Override
    public boolean containsTags(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      return internalGetTags().getMap().containsKey(key);
    }
    /**
     * Use {@link #getTagsMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String> getTags() {
      return getTagsMap();
    }
    /**
     * <code>map&lt;string, string&gt; tags = 6;</code>
     */
    @java.lang.Override
    public java.util.Map<java.lang.String, java.lang.String> getTagsMap() {
      return internalGetTags().getMap();
    }
    /**
     * <code>map&lt;string, string&gt; tags = 6;</code>
     */
    @java.lang.Override
    public /* nullable */
java.lang.String getTagsOrDefault(
        java.lang.String key,
        /* nullable */
java.lang.String defaultValue) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetTags().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, string&gt; tags = 6;</code>
     */
    @java.lang.Override
    public java.lang.String getTagsOrThrow(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetTags().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }
    public Builder clearTags() {
      bitField0_ = (bitField0_ & ~0x00000020);
      internalGetMutableTags().getMutableMap()
          .clear();
      return this;
    }
    /**
     * <code>map&lt;string, string&gt; tags = 6;</code>
     */
    public Builder removeTags(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      internalGetMutableTags().getMutableMap()
          .remove(key);
      return this;
    }
    /**
     * Use alternate mutation accessors instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String>
        getMutableTags() {
      bitField0_ |= 0x00000020;
      return internalGetMutableTags().getMutableMap();
    }
    /**
     * <code>map&lt;string, string&gt; tags = 6;</code>
     */
    public Builder putTags(
        java.lang.String key,
        java.lang.String value) {
      if (key == null) { throw new NullPointerException("map key"); }
      if (value == null) { throw new NullPointerException("map value"); }
      internalGetMutableTags().getMutableMap()
          .put(key, value);
      bitField0_ |= 0x00000020;
      return this;
    }
    /**
     * <code>map&lt;string, string&gt; tags = 6;</code>
     */
    public Builder putAllTags(
        java.util.Map<java.lang.String, java.lang.String> values) {
      internalGetMutableTags().getMutableMap()
          .putAll(values);
      bitField0_ |= 0x00000020;
      return this;
    }

    private java.lang.Object agentVersion_ = "";
    /**
     * <code>string agentVersion = 7;</code>
     * @return The agentVersion.
     */
    public java.lang.String getAgentVersion() {
      java.lang.Object ref = agentVersion_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        agentVersion_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string agentVersion = 7;</code>
     * @return The bytes for agentVersion.
     */
    public com.google.protobuf.ByteString
        getAgentVersionBytes() {
      java.lang.Object ref = agentVersion_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        agentVersion_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string agentVersion = 7;</code>
     * @param value The agentVersion to set.
     * @return This builder for chaining.
     */
    public Builder setAgentVersion(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      agentVersion_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <code>string agentVersion = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearAgentVersion() {
      agentVersion_ = getDefaultInstance().getAgentVersion();
      bitField0_ = (bitField0_ & ~0x00000040);
      onChanged();
      return this;
    }
    /**
     * <code>string agentVersion = 7;</code>
     * @param value The bytes for agentVersion to set.
     * @return This builder for chaining.
     */
    public Builder setAgentVersionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      agentVersion_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:pb.APITracePayload)
  }

  // @@protoc_insertion_point(class_scope:pb.APITracePayload)
  private static final com.dd.agent.pb.APITracePayload DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.dd.agent.pb.APITracePayload();
  }

  public static com.dd.agent.pb.APITracePayload getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<APITracePayload>
      PARSER = new com.google.protobuf.AbstractParser<APITracePayload>() {
    @java.lang.Override
    public APITracePayload parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<APITracePayload> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<APITracePayload> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.dd.agent.pb.APITracePayload getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

