// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/resources/protos/trace.proto

package com.dd.agent.pb;

/**
 * Protobuf type {@code pb.APITrace}
 */
public final class APITrace extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:pb.APITrace)
    APITraceOrBuilder {
private static final long serialVersionUID = 0L;
  // Use APITrace.newBuilder() to construct.
  private APITrace(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private APITrace() {
    spans_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new APITrace();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.dd.agent.pb.APITraceProto.internal_static_pb_APITrace_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.dd.agent.pb.APITraceProto.internal_static_pb_APITrace_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.dd.agent.pb.APITrace.class, com.dd.agent.pb.APITrace.Builder.class);
  }

  public static final int TRACEID_FIELD_NUMBER = 1;
  private long traceID_ = 0L;
  /**
   * <code>uint64 traceID = 1;</code>
   * @return The traceID.
   */
  @java.lang.Override
  public long getTraceID() {
    return traceID_;
  }

  public static final int SPANS_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private java.util.List<com.dd.agent.pb.APISpan> spans_;
  /**
   * <code>repeated .pb.APISpan spans = 2;</code>
   */
  @java.lang.Override
  public java.util.List<com.dd.agent.pb.APISpan> getSpansList() {
    return spans_;
  }
  /**
   * <code>repeated .pb.APISpan spans = 2;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.dd.agent.pb.APISpanOrBuilder> 
      getSpansOrBuilderList() {
    return spans_;
  }
  /**
   * <code>repeated .pb.APISpan spans = 2;</code>
   */
  @java.lang.Override
  public int getSpansCount() {
    return spans_.size();
  }
  /**
   * <code>repeated .pb.APISpan spans = 2;</code>
   */
  @java.lang.Override
  public com.dd.agent.pb.APISpan getSpans(int index) {
    return spans_.get(index);
  }
  /**
   * <code>repeated .pb.APISpan spans = 2;</code>
   */
  @java.lang.Override
  public com.dd.agent.pb.APISpanOrBuilder getSpansOrBuilder(
      int index) {
    return spans_.get(index);
  }

  public static final int STARTTIME_FIELD_NUMBER = 6;
  private long startTime_ = 0L;
  /**
   * <code>int64 startTime = 6;</code>
   * @return The startTime.
   */
  @java.lang.Override
  public long getStartTime() {
    return startTime_;
  }

  public static final int ENDTIME_FIELD_NUMBER = 7;
  private long endTime_ = 0L;
  /**
   * <code>int64 endTime = 7;</code>
   * @return The endTime.
   */
  @java.lang.Override
  public long getEndTime() {
    return endTime_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (traceID_ != 0L) {
      output.writeUInt64(1, traceID_);
    }
    for (int i = 0; i < spans_.size(); i++) {
      output.writeMessage(2, spans_.get(i));
    }
    if (startTime_ != 0L) {
      output.writeInt64(6, startTime_);
    }
    if (endTime_ != 0L) {
      output.writeInt64(7, endTime_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (traceID_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(1, traceID_);
    }
    for (int i = 0; i < spans_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, spans_.get(i));
    }
    if (startTime_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(6, startTime_);
    }
    if (endTime_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(7, endTime_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.dd.agent.pb.APITrace)) {
      return super.equals(obj);
    }
    com.dd.agent.pb.APITrace other = (com.dd.agent.pb.APITrace) obj;

    if (getTraceID()
        != other.getTraceID()) return false;
    if (!getSpansList()
        .equals(other.getSpansList())) return false;
    if (getStartTime()
        != other.getStartTime()) return false;
    if (getEndTime()
        != other.getEndTime()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + TRACEID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getTraceID());
    if (getSpansCount() > 0) {
      hash = (37 * hash) + SPANS_FIELD_NUMBER;
      hash = (53 * hash) + getSpansList().hashCode();
    }
    hash = (37 * hash) + STARTTIME_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getStartTime());
    hash = (37 * hash) + ENDTIME_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getEndTime());
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.dd.agent.pb.APITrace parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.dd.agent.pb.APITrace parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.dd.agent.pb.APITrace parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.dd.agent.pb.APITrace parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.dd.agent.pb.APITrace parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.dd.agent.pb.APITrace parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.dd.agent.pb.APITrace parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.dd.agent.pb.APITrace parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.dd.agent.pb.APITrace parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.dd.agent.pb.APITrace parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.dd.agent.pb.APITrace parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.dd.agent.pb.APITrace parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.dd.agent.pb.APITrace prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code pb.APITrace}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:pb.APITrace)
      com.dd.agent.pb.APITraceOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.dd.agent.pb.APITraceProto.internal_static_pb_APITrace_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.dd.agent.pb.APITraceProto.internal_static_pb_APITrace_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.dd.agent.pb.APITrace.class, com.dd.agent.pb.APITrace.Builder.class);
    }

    // Construct using com.dd.agent.pb.APITrace.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      traceID_ = 0L;
      if (spansBuilder_ == null) {
        spans_ = java.util.Collections.emptyList();
      } else {
        spans_ = null;
        spansBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000002);
      startTime_ = 0L;
      endTime_ = 0L;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.dd.agent.pb.APITraceProto.internal_static_pb_APITrace_descriptor;
    }

    @java.lang.Override
    public com.dd.agent.pb.APITrace getDefaultInstanceForType() {
      return com.dd.agent.pb.APITrace.getDefaultInstance();
    }

    @java.lang.Override
    public com.dd.agent.pb.APITrace build() {
      com.dd.agent.pb.APITrace result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.dd.agent.pb.APITrace buildPartial() {
      com.dd.agent.pb.APITrace result = new com.dd.agent.pb.APITrace(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(com.dd.agent.pb.APITrace result) {
      if (spansBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0)) {
          spans_ = java.util.Collections.unmodifiableList(spans_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.spans_ = spans_;
      } else {
        result.spans_ = spansBuilder_.build();
      }
    }

    private void buildPartial0(com.dd.agent.pb.APITrace result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.traceID_ = traceID_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.startTime_ = startTime_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.endTime_ = endTime_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.dd.agent.pb.APITrace) {
        return mergeFrom((com.dd.agent.pb.APITrace)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.dd.agent.pb.APITrace other) {
      if (other == com.dd.agent.pb.APITrace.getDefaultInstance()) return this;
      if (other.getTraceID() != 0L) {
        setTraceID(other.getTraceID());
      }
      if (spansBuilder_ == null) {
        if (!other.spans_.isEmpty()) {
          if (spans_.isEmpty()) {
            spans_ = other.spans_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureSpansIsMutable();
            spans_.addAll(other.spans_);
          }
          onChanged();
        }
      } else {
        if (!other.spans_.isEmpty()) {
          if (spansBuilder_.isEmpty()) {
            spansBuilder_.dispose();
            spansBuilder_ = null;
            spans_ = other.spans_;
            bitField0_ = (bitField0_ & ~0x00000002);
            spansBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getSpansFieldBuilder() : null;
          } else {
            spansBuilder_.addAllMessages(other.spans_);
          }
        }
      }
      if (other.getStartTime() != 0L) {
        setStartTime(other.getStartTime());
      }
      if (other.getEndTime() != 0L) {
        setEndTime(other.getEndTime());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              traceID_ = input.readUInt64();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 18: {
              com.dd.agent.pb.APISpan m =
                  input.readMessage(
                      com.dd.agent.pb.APISpan.parser(),
                      extensionRegistry);
              if (spansBuilder_ == null) {
                ensureSpansIsMutable();
                spans_.add(m);
              } else {
                spansBuilder_.addMessage(m);
              }
              break;
            } // case 18
            case 48: {
              startTime_ = input.readInt64();
              bitField0_ |= 0x00000004;
              break;
            } // case 48
            case 56: {
              endTime_ = input.readInt64();
              bitField0_ |= 0x00000008;
              break;
            } // case 56
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private long traceID_ ;
    /**
     * <code>uint64 traceID = 1;</code>
     * @return The traceID.
     */
    @java.lang.Override
    public long getTraceID() {
      return traceID_;
    }
    /**
     * <code>uint64 traceID = 1;</code>
     * @param value The traceID to set.
     * @return This builder for chaining.
     */
    public Builder setTraceID(long value) {
      
      traceID_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>uint64 traceID = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearTraceID() {
      bitField0_ = (bitField0_ & ~0x00000001);
      traceID_ = 0L;
      onChanged();
      return this;
    }

    private java.util.List<com.dd.agent.pb.APISpan> spans_ =
      java.util.Collections.emptyList();
    private void ensureSpansIsMutable() {
      if (!((bitField0_ & 0x00000002) != 0)) {
        spans_ = new java.util.ArrayList<com.dd.agent.pb.APISpan>(spans_);
        bitField0_ |= 0x00000002;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.dd.agent.pb.APISpan, com.dd.agent.pb.APISpan.Builder, com.dd.agent.pb.APISpanOrBuilder> spansBuilder_;

    /**
     * <code>repeated .pb.APISpan spans = 2;</code>
     */
    public java.util.List<com.dd.agent.pb.APISpan> getSpansList() {
      if (spansBuilder_ == null) {
        return java.util.Collections.unmodifiableList(spans_);
      } else {
        return spansBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .pb.APISpan spans = 2;</code>
     */
    public int getSpansCount() {
      if (spansBuilder_ == null) {
        return spans_.size();
      } else {
        return spansBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .pb.APISpan spans = 2;</code>
     */
    public com.dd.agent.pb.APISpan getSpans(int index) {
      if (spansBuilder_ == null) {
        return spans_.get(index);
      } else {
        return spansBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .pb.APISpan spans = 2;</code>
     */
    public Builder setSpans(
        int index, com.dd.agent.pb.APISpan value) {
      if (spansBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSpansIsMutable();
        spans_.set(index, value);
        onChanged();
      } else {
        spansBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .pb.APISpan spans = 2;</code>
     */
    public Builder setSpans(
        int index, com.dd.agent.pb.APISpan.Builder builderForValue) {
      if (spansBuilder_ == null) {
        ensureSpansIsMutable();
        spans_.set(index, builderForValue.build());
        onChanged();
      } else {
        spansBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .pb.APISpan spans = 2;</code>
     */
    public Builder addSpans(com.dd.agent.pb.APISpan value) {
      if (spansBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSpansIsMutable();
        spans_.add(value);
        onChanged();
      } else {
        spansBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .pb.APISpan spans = 2;</code>
     */
    public Builder addSpans(
        int index, com.dd.agent.pb.APISpan value) {
      if (spansBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSpansIsMutable();
        spans_.add(index, value);
        onChanged();
      } else {
        spansBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .pb.APISpan spans = 2;</code>
     */
    public Builder addSpans(
        com.dd.agent.pb.APISpan.Builder builderForValue) {
      if (spansBuilder_ == null) {
        ensureSpansIsMutable();
        spans_.add(builderForValue.build());
        onChanged();
      } else {
        spansBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .pb.APISpan spans = 2;</code>
     */
    public Builder addSpans(
        int index, com.dd.agent.pb.APISpan.Builder builderForValue) {
      if (spansBuilder_ == null) {
        ensureSpansIsMutable();
        spans_.add(index, builderForValue.build());
        onChanged();
      } else {
        spansBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .pb.APISpan spans = 2;</code>
     */
    public Builder addAllSpans(
        java.lang.Iterable<? extends com.dd.agent.pb.APISpan> values) {
      if (spansBuilder_ == null) {
        ensureSpansIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, spans_);
        onChanged();
      } else {
        spansBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .pb.APISpan spans = 2;</code>
     */
    public Builder clearSpans() {
      if (spansBuilder_ == null) {
        spans_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
      } else {
        spansBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .pb.APISpan spans = 2;</code>
     */
    public Builder removeSpans(int index) {
      if (spansBuilder_ == null) {
        ensureSpansIsMutable();
        spans_.remove(index);
        onChanged();
      } else {
        spansBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .pb.APISpan spans = 2;</code>
     */
    public com.dd.agent.pb.APISpan.Builder getSpansBuilder(
        int index) {
      return getSpansFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .pb.APISpan spans = 2;</code>
     */
    public com.dd.agent.pb.APISpanOrBuilder getSpansOrBuilder(
        int index) {
      if (spansBuilder_ == null) {
        return spans_.get(index);  } else {
        return spansBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .pb.APISpan spans = 2;</code>
     */
    public java.util.List<? extends com.dd.agent.pb.APISpanOrBuilder> 
         getSpansOrBuilderList() {
      if (spansBuilder_ != null) {
        return spansBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(spans_);
      }
    }
    /**
     * <code>repeated .pb.APISpan spans = 2;</code>
     */
    public com.dd.agent.pb.APISpan.Builder addSpansBuilder() {
      return getSpansFieldBuilder().addBuilder(
          com.dd.agent.pb.APISpan.getDefaultInstance());
    }
    /**
     * <code>repeated .pb.APISpan spans = 2;</code>
     */
    public com.dd.agent.pb.APISpan.Builder addSpansBuilder(
        int index) {
      return getSpansFieldBuilder().addBuilder(
          index, com.dd.agent.pb.APISpan.getDefaultInstance());
    }
    /**
     * <code>repeated .pb.APISpan spans = 2;</code>
     */
    public java.util.List<com.dd.agent.pb.APISpan.Builder> 
         getSpansBuilderList() {
      return getSpansFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.dd.agent.pb.APISpan, com.dd.agent.pb.APISpan.Builder, com.dd.agent.pb.APISpanOrBuilder> 
        getSpansFieldBuilder() {
      if (spansBuilder_ == null) {
        spansBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.dd.agent.pb.APISpan, com.dd.agent.pb.APISpan.Builder, com.dd.agent.pb.APISpanOrBuilder>(
                spans_,
                ((bitField0_ & 0x00000002) != 0),
                getParentForChildren(),
                isClean());
        spans_ = null;
      }
      return spansBuilder_;
    }

    private long startTime_ ;
    /**
     * <code>int64 startTime = 6;</code>
     * @return The startTime.
     */
    @java.lang.Override
    public long getStartTime() {
      return startTime_;
    }
    /**
     * <code>int64 startTime = 6;</code>
     * @param value The startTime to set.
     * @return This builder for chaining.
     */
    public Builder setStartTime(long value) {
      
      startTime_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>int64 startTime = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearStartTime() {
      bitField0_ = (bitField0_ & ~0x00000004);
      startTime_ = 0L;
      onChanged();
      return this;
    }

    private long endTime_ ;
    /**
     * <code>int64 endTime = 7;</code>
     * @return The endTime.
     */
    @java.lang.Override
    public long getEndTime() {
      return endTime_;
    }
    /**
     * <code>int64 endTime = 7;</code>
     * @param value The endTime to set.
     * @return This builder for chaining.
     */
    public Builder setEndTime(long value) {
      
      endTime_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>int64 endTime = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearEndTime() {
      bitField0_ = (bitField0_ & ~0x00000008);
      endTime_ = 0L;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:pb.APITrace)
  }

  // @@protoc_insertion_point(class_scope:pb.APITrace)
  private static final com.dd.agent.pb.APITrace DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.dd.agent.pb.APITrace();
  }

  public static com.dd.agent.pb.APITrace getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<APITrace>
      PARSER = new com.google.protobuf.AbstractParser<APITrace>() {
    @java.lang.Override
    public APITrace parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<APITrace> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<APITrace> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.dd.agent.pb.APITrace getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

