// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/resources/protos/trace.proto

package com.dd.agent.pb;

/**
 * Protobuf type {@code pb.APITracerPayload}
 */
public final class APITracerPayload extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:pb.APITracerPayload)
    APITracerPayloadOrBuilder {
private static final long serialVersionUID = 0L;
  // Use APITracerPayload.newBuilder() to construct.
  private APITracerPayload(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private APITracerPayload() {
    containerID_ = "";
    languageName_ = "";
    languageVersion_ = "";
    tracerVersion_ = "";
    runtimeID_ = "";
    chunks_ = java.util.Collections.emptyList();
    env_ = "";
    hostname_ = "";
    appVersion_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new APITracerPayload();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.dd.agent.pb.APITraceProto.internal_static_pb_APITracerPayload_descriptor;
  }

  @SuppressWarnings({"rawtypes"})
  @java.lang.Override
  protected com.google.protobuf.MapField internalGetMapField(
      int number) {
    switch (number) {
      case 7:
        return internalGetTags();
      default:
        throw new RuntimeException(
            "Invalid map field number: " + number);
    }
  }
  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.dd.agent.pb.APITraceProto.internal_static_pb_APITracerPayload_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.dd.agent.pb.APITracerPayload.class, com.dd.agent.pb.APITracerPayload.Builder.class);
  }

  public static final int CONTAINERID_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object containerID_ = "";
  /**
   * <code>string containerID = 1;</code>
   * @return The containerID.
   */
  @java.lang.Override
  public java.lang.String getContainerID() {
    java.lang.Object ref = containerID_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      containerID_ = s;
      return s;
    }
  }
  /**
   * <code>string containerID = 1;</code>
   * @return The bytes for containerID.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getContainerIDBytes() {
    java.lang.Object ref = containerID_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      containerID_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int LANGUAGENAME_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object languageName_ = "";
  /**
   * <code>string languageName = 2;</code>
   * @return The languageName.
   */
  @java.lang.Override
  public java.lang.String getLanguageName() {
    java.lang.Object ref = languageName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      languageName_ = s;
      return s;
    }
  }
  /**
   * <code>string languageName = 2;</code>
   * @return The bytes for languageName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getLanguageNameBytes() {
    java.lang.Object ref = languageName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      languageName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int LANGUAGEVERSION_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object languageVersion_ = "";
  /**
   * <code>string languageVersion = 3;</code>
   * @return The languageVersion.
   */
  @java.lang.Override
  public java.lang.String getLanguageVersion() {
    java.lang.Object ref = languageVersion_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      languageVersion_ = s;
      return s;
    }
  }
  /**
   * <code>string languageVersion = 3;</code>
   * @return The bytes for languageVersion.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getLanguageVersionBytes() {
    java.lang.Object ref = languageVersion_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      languageVersion_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TRACERVERSION_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private volatile java.lang.Object tracerVersion_ = "";
  /**
   * <code>string tracerVersion = 4;</code>
   * @return The tracerVersion.
   */
  @java.lang.Override
  public java.lang.String getTracerVersion() {
    java.lang.Object ref = tracerVersion_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      tracerVersion_ = s;
      return s;
    }
  }
  /**
   * <code>string tracerVersion = 4;</code>
   * @return The bytes for tracerVersion.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTracerVersionBytes() {
    java.lang.Object ref = tracerVersion_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      tracerVersion_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int RUNTIMEID_FIELD_NUMBER = 5;
  @SuppressWarnings("serial")
  private volatile java.lang.Object runtimeID_ = "";
  /**
   * <code>string runtimeID = 5;</code>
   * @return The runtimeID.
   */
  @java.lang.Override
  public java.lang.String getRuntimeID() {
    java.lang.Object ref = runtimeID_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      runtimeID_ = s;
      return s;
    }
  }
  /**
   * <code>string runtimeID = 5;</code>
   * @return The bytes for runtimeID.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getRuntimeIDBytes() {
    java.lang.Object ref = runtimeID_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      runtimeID_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CHUNKS_FIELD_NUMBER = 6;
  @SuppressWarnings("serial")
  private java.util.List<com.dd.agent.pb.APITraceChunk> chunks_;
  /**
   * <code>repeated .pb.APITraceChunk chunks = 6;</code>
   */
  @java.lang.Override
  public java.util.List<com.dd.agent.pb.APITraceChunk> getChunksList() {
    return chunks_;
  }
  /**
   * <code>repeated .pb.APITraceChunk chunks = 6;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.dd.agent.pb.APITraceChunkOrBuilder> 
      getChunksOrBuilderList() {
    return chunks_;
  }
  /**
   * <code>repeated .pb.APITraceChunk chunks = 6;</code>
   */
  @java.lang.Override
  public int getChunksCount() {
    return chunks_.size();
  }
  /**
   * <code>repeated .pb.APITraceChunk chunks = 6;</code>
   */
  @java.lang.Override
  public com.dd.agent.pb.APITraceChunk getChunks(int index) {
    return chunks_.get(index);
  }
  /**
   * <code>repeated .pb.APITraceChunk chunks = 6;</code>
   */
  @java.lang.Override
  public com.dd.agent.pb.APITraceChunkOrBuilder getChunksOrBuilder(
      int index) {
    return chunks_.get(index);
  }

  public static final int TAGS_FIELD_NUMBER = 7;
  private static final class TagsDefaultEntryHolder {
    static final com.google.protobuf.MapEntry<
        java.lang.String, java.lang.String> defaultEntry =
            com.google.protobuf.MapEntry
            .<java.lang.String, java.lang.String>newDefaultInstance(
                com.dd.agent.pb.APITraceProto.internal_static_pb_APITracerPayload_TagsEntry_descriptor, 
                com.google.protobuf.WireFormat.FieldType.STRING,
                "",
                com.google.protobuf.WireFormat.FieldType.STRING,
                "");
  }
  @SuppressWarnings("serial")
  private com.google.protobuf.MapField<
      java.lang.String, java.lang.String> tags_;
  private com.google.protobuf.MapField<java.lang.String, java.lang.String>
  internalGetTags() {
    if (tags_ == null) {
      return com.google.protobuf.MapField.emptyMapField(
          TagsDefaultEntryHolder.defaultEntry);
    }
    return tags_;
  }
  public int getTagsCount() {
    return internalGetTags().getMap().size();
  }
  /**
   * <code>map&lt;string, string&gt; tags = 7;</code>
   */
  @java.lang.Override
  public boolean containsTags(
      java.lang.String key) {
    if (key == null) { throw new NullPointerException("map key"); }
    return internalGetTags().getMap().containsKey(key);
  }
  /**
   * Use {@link #getTagsMap()} instead.
   */
  @java.lang.Override
  @java.lang.Deprecated
  public java.util.Map<java.lang.String, java.lang.String> getTags() {
    return getTagsMap();
  }
  /**
   * <code>map&lt;string, string&gt; tags = 7;</code>
   */
  @java.lang.Override
  public java.util.Map<java.lang.String, java.lang.String> getTagsMap() {
    return internalGetTags().getMap();
  }
  /**
   * <code>map&lt;string, string&gt; tags = 7;</code>
   */
  @java.lang.Override
  public /* nullable */
java.lang.String getTagsOrDefault(
      java.lang.String key,
      /* nullable */
java.lang.String defaultValue) {
    if (key == null) { throw new NullPointerException("map key"); }
    java.util.Map<java.lang.String, java.lang.String> map =
        internalGetTags().getMap();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }
  /**
   * <code>map&lt;string, string&gt; tags = 7;</code>
   */
  @java.lang.Override
  public java.lang.String getTagsOrThrow(
      java.lang.String key) {
    if (key == null) { throw new NullPointerException("map key"); }
    java.util.Map<java.lang.String, java.lang.String> map =
        internalGetTags().getMap();
    if (!map.containsKey(key)) {
      throw new java.lang.IllegalArgumentException();
    }
    return map.get(key);
  }

  public static final int ENV_FIELD_NUMBER = 8;
  @SuppressWarnings("serial")
  private volatile java.lang.Object env_ = "";
  /**
   * <code>string env = 8;</code>
   * @return The env.
   */
  @java.lang.Override
  public java.lang.String getEnv() {
    java.lang.Object ref = env_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      env_ = s;
      return s;
    }
  }
  /**
   * <code>string env = 8;</code>
   * @return The bytes for env.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getEnvBytes() {
    java.lang.Object ref = env_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      env_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int HOSTNAME_FIELD_NUMBER = 9;
  @SuppressWarnings("serial")
  private volatile java.lang.Object hostname_ = "";
  /**
   * <code>string hostname = 9;</code>
   * @return The hostname.
   */
  @java.lang.Override
  public java.lang.String getHostname() {
    java.lang.Object ref = hostname_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      hostname_ = s;
      return s;
    }
  }
  /**
   * <code>string hostname = 9;</code>
   * @return The bytes for hostname.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getHostnameBytes() {
    java.lang.Object ref = hostname_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      hostname_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int APPVERSION_FIELD_NUMBER = 10;
  @SuppressWarnings("serial")
  private volatile java.lang.Object appVersion_ = "";
  /**
   * <code>string appVersion = 10;</code>
   * @return The appVersion.
   */
  @java.lang.Override
  public java.lang.String getAppVersion() {
    java.lang.Object ref = appVersion_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      appVersion_ = s;
      return s;
    }
  }
  /**
   * <code>string appVersion = 10;</code>
   * @return The bytes for appVersion.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getAppVersionBytes() {
    java.lang.Object ref = appVersion_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      appVersion_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(containerID_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, containerID_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(languageName_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, languageName_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(languageVersion_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, languageVersion_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(tracerVersion_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, tracerVersion_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(runtimeID_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, runtimeID_);
    }
    for (int i = 0; i < chunks_.size(); i++) {
      output.writeMessage(6, chunks_.get(i));
    }
    com.google.protobuf.GeneratedMessageV3
      .serializeStringMapTo(
        output,
        internalGetTags(),
        TagsDefaultEntryHolder.defaultEntry,
        7);
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(env_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 8, env_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(hostname_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 9, hostname_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(appVersion_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 10, appVersion_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(containerID_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, containerID_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(languageName_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, languageName_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(languageVersion_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, languageVersion_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(tracerVersion_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, tracerVersion_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(runtimeID_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, runtimeID_);
    }
    for (int i = 0; i < chunks_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(6, chunks_.get(i));
    }
    for (java.util.Map.Entry<java.lang.String, java.lang.String> entry
         : internalGetTags().getMap().entrySet()) {
      com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
      tags__ = TagsDefaultEntryHolder.defaultEntry.newBuilderForType()
          .setKey(entry.getKey())
          .setValue(entry.getValue())
          .build();
      size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(7, tags__);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(env_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, env_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(hostname_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(9, hostname_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(appVersion_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(10, appVersion_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.dd.agent.pb.APITracerPayload)) {
      return super.equals(obj);
    }
    com.dd.agent.pb.APITracerPayload other = (com.dd.agent.pb.APITracerPayload) obj;

    if (!getContainerID()
        .equals(other.getContainerID())) return false;
    if (!getLanguageName()
        .equals(other.getLanguageName())) return false;
    if (!getLanguageVersion()
        .equals(other.getLanguageVersion())) return false;
    if (!getTracerVersion()
        .equals(other.getTracerVersion())) return false;
    if (!getRuntimeID()
        .equals(other.getRuntimeID())) return false;
    if (!getChunksList()
        .equals(other.getChunksList())) return false;
    if (!internalGetTags().equals(
        other.internalGetTags())) return false;
    if (!getEnv()
        .equals(other.getEnv())) return false;
    if (!getHostname()
        .equals(other.getHostname())) return false;
    if (!getAppVersion()
        .equals(other.getAppVersion())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + CONTAINERID_FIELD_NUMBER;
    hash = (53 * hash) + getContainerID().hashCode();
    hash = (37 * hash) + LANGUAGENAME_FIELD_NUMBER;
    hash = (53 * hash) + getLanguageName().hashCode();
    hash = (37 * hash) + LANGUAGEVERSION_FIELD_NUMBER;
    hash = (53 * hash) + getLanguageVersion().hashCode();
    hash = (37 * hash) + TRACERVERSION_FIELD_NUMBER;
    hash = (53 * hash) + getTracerVersion().hashCode();
    hash = (37 * hash) + RUNTIMEID_FIELD_NUMBER;
    hash = (53 * hash) + getRuntimeID().hashCode();
    if (getChunksCount() > 0) {
      hash = (37 * hash) + CHUNKS_FIELD_NUMBER;
      hash = (53 * hash) + getChunksList().hashCode();
    }
    if (!internalGetTags().getMap().isEmpty()) {
      hash = (37 * hash) + TAGS_FIELD_NUMBER;
      hash = (53 * hash) + internalGetTags().hashCode();
    }
    hash = (37 * hash) + ENV_FIELD_NUMBER;
    hash = (53 * hash) + getEnv().hashCode();
    hash = (37 * hash) + HOSTNAME_FIELD_NUMBER;
    hash = (53 * hash) + getHostname().hashCode();
    hash = (37 * hash) + APPVERSION_FIELD_NUMBER;
    hash = (53 * hash) + getAppVersion().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.dd.agent.pb.APITracerPayload parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.dd.agent.pb.APITracerPayload parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.dd.agent.pb.APITracerPayload parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.dd.agent.pb.APITracerPayload parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.dd.agent.pb.APITracerPayload parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.dd.agent.pb.APITracerPayload parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.dd.agent.pb.APITracerPayload parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.dd.agent.pb.APITracerPayload parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.dd.agent.pb.APITracerPayload parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.dd.agent.pb.APITracerPayload parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.dd.agent.pb.APITracerPayload parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.dd.agent.pb.APITracerPayload parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.dd.agent.pb.APITracerPayload prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code pb.APITracerPayload}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:pb.APITracerPayload)
      com.dd.agent.pb.APITracerPayloadOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.dd.agent.pb.APITraceProto.internal_static_pb_APITracerPayload_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 7:
          return internalGetTags();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMutableMapField(
        int number) {
      switch (number) {
        case 7:
          return internalGetMutableTags();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.dd.agent.pb.APITraceProto.internal_static_pb_APITracerPayload_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.dd.agent.pb.APITracerPayload.class, com.dd.agent.pb.APITracerPayload.Builder.class);
    }

    // Construct using com.dd.agent.pb.APITracerPayload.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      containerID_ = "";
      languageName_ = "";
      languageVersion_ = "";
      tracerVersion_ = "";
      runtimeID_ = "";
      if (chunksBuilder_ == null) {
        chunks_ = java.util.Collections.emptyList();
      } else {
        chunks_ = null;
        chunksBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000020);
      internalGetMutableTags().clear();
      env_ = "";
      hostname_ = "";
      appVersion_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.dd.agent.pb.APITraceProto.internal_static_pb_APITracerPayload_descriptor;
    }

    @java.lang.Override
    public com.dd.agent.pb.APITracerPayload getDefaultInstanceForType() {
      return com.dd.agent.pb.APITracerPayload.getDefaultInstance();
    }

    @java.lang.Override
    public com.dd.agent.pb.APITracerPayload build() {
      com.dd.agent.pb.APITracerPayload result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.dd.agent.pb.APITracerPayload buildPartial() {
      com.dd.agent.pb.APITracerPayload result = new com.dd.agent.pb.APITracerPayload(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(com.dd.agent.pb.APITracerPayload result) {
      if (chunksBuilder_ == null) {
        if (((bitField0_ & 0x00000020) != 0)) {
          chunks_ = java.util.Collections.unmodifiableList(chunks_);
          bitField0_ = (bitField0_ & ~0x00000020);
        }
        result.chunks_ = chunks_;
      } else {
        result.chunks_ = chunksBuilder_.build();
      }
    }

    private void buildPartial0(com.dd.agent.pb.APITracerPayload result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.containerID_ = containerID_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.languageName_ = languageName_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.languageVersion_ = languageVersion_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.tracerVersion_ = tracerVersion_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.runtimeID_ = runtimeID_;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.tags_ = internalGetTags();
        result.tags_.makeImmutable();
      }
      if (((from_bitField0_ & 0x00000080) != 0)) {
        result.env_ = env_;
      }
      if (((from_bitField0_ & 0x00000100) != 0)) {
        result.hostname_ = hostname_;
      }
      if (((from_bitField0_ & 0x00000200) != 0)) {
        result.appVersion_ = appVersion_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.dd.agent.pb.APITracerPayload) {
        return mergeFrom((com.dd.agent.pb.APITracerPayload)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.dd.agent.pb.APITracerPayload other) {
      if (other == com.dd.agent.pb.APITracerPayload.getDefaultInstance()) return this;
      if (!other.getContainerID().isEmpty()) {
        containerID_ = other.containerID_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.getLanguageName().isEmpty()) {
        languageName_ = other.languageName_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (!other.getLanguageVersion().isEmpty()) {
        languageVersion_ = other.languageVersion_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (!other.getTracerVersion().isEmpty()) {
        tracerVersion_ = other.tracerVersion_;
        bitField0_ |= 0x00000008;
        onChanged();
      }
      if (!other.getRuntimeID().isEmpty()) {
        runtimeID_ = other.runtimeID_;
        bitField0_ |= 0x00000010;
        onChanged();
      }
      if (chunksBuilder_ == null) {
        if (!other.chunks_.isEmpty()) {
          if (chunks_.isEmpty()) {
            chunks_ = other.chunks_;
            bitField0_ = (bitField0_ & ~0x00000020);
          } else {
            ensureChunksIsMutable();
            chunks_.addAll(other.chunks_);
          }
          onChanged();
        }
      } else {
        if (!other.chunks_.isEmpty()) {
          if (chunksBuilder_.isEmpty()) {
            chunksBuilder_.dispose();
            chunksBuilder_ = null;
            chunks_ = other.chunks_;
            bitField0_ = (bitField0_ & ~0x00000020);
            chunksBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getChunksFieldBuilder() : null;
          } else {
            chunksBuilder_.addAllMessages(other.chunks_);
          }
        }
      }
      internalGetMutableTags().mergeFrom(
          other.internalGetTags());
      bitField0_ |= 0x00000040;
      if (!other.getEnv().isEmpty()) {
        env_ = other.env_;
        bitField0_ |= 0x00000080;
        onChanged();
      }
      if (!other.getHostname().isEmpty()) {
        hostname_ = other.hostname_;
        bitField0_ |= 0x00000100;
        onChanged();
      }
      if (!other.getAppVersion().isEmpty()) {
        appVersion_ = other.appVersion_;
        bitField0_ |= 0x00000200;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              containerID_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              languageName_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              languageVersion_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 34: {
              tracerVersion_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            case 42: {
              runtimeID_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000010;
              break;
            } // case 42
            case 50: {
              com.dd.agent.pb.APITraceChunk m =
                  input.readMessage(
                      com.dd.agent.pb.APITraceChunk.parser(),
                      extensionRegistry);
              if (chunksBuilder_ == null) {
                ensureChunksIsMutable();
                chunks_.add(m);
              } else {
                chunksBuilder_.addMessage(m);
              }
              break;
            } // case 50
            case 58: {
              com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
              tags__ = input.readMessage(
                  TagsDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              internalGetMutableTags().getMutableMap().put(
                  tags__.getKey(), tags__.getValue());
              bitField0_ |= 0x00000040;
              break;
            } // case 58
            case 66: {
              env_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000080;
              break;
            } // case 66
            case 74: {
              hostname_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000100;
              break;
            } // case 74
            case 82: {
              appVersion_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000200;
              break;
            } // case 82
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object containerID_ = "";
    /**
     * <code>string containerID = 1;</code>
     * @return The containerID.
     */
    public java.lang.String getContainerID() {
      java.lang.Object ref = containerID_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        containerID_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string containerID = 1;</code>
     * @return The bytes for containerID.
     */
    public com.google.protobuf.ByteString
        getContainerIDBytes() {
      java.lang.Object ref = containerID_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        containerID_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string containerID = 1;</code>
     * @param value The containerID to set.
     * @return This builder for chaining.
     */
    public Builder setContainerID(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      containerID_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string containerID = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearContainerID() {
      containerID_ = getDefaultInstance().getContainerID();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string containerID = 1;</code>
     * @param value The bytes for containerID to set.
     * @return This builder for chaining.
     */
    public Builder setContainerIDBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      containerID_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object languageName_ = "";
    /**
     * <code>string languageName = 2;</code>
     * @return The languageName.
     */
    public java.lang.String getLanguageName() {
      java.lang.Object ref = languageName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        languageName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string languageName = 2;</code>
     * @return The bytes for languageName.
     */
    public com.google.protobuf.ByteString
        getLanguageNameBytes() {
      java.lang.Object ref = languageName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        languageName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string languageName = 2;</code>
     * @param value The languageName to set.
     * @return This builder for chaining.
     */
    public Builder setLanguageName(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      languageName_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string languageName = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearLanguageName() {
      languageName_ = getDefaultInstance().getLanguageName();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string languageName = 2;</code>
     * @param value The bytes for languageName to set.
     * @return This builder for chaining.
     */
    public Builder setLanguageNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      languageName_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private java.lang.Object languageVersion_ = "";
    /**
     * <code>string languageVersion = 3;</code>
     * @return The languageVersion.
     */
    public java.lang.String getLanguageVersion() {
      java.lang.Object ref = languageVersion_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        languageVersion_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string languageVersion = 3;</code>
     * @return The bytes for languageVersion.
     */
    public com.google.protobuf.ByteString
        getLanguageVersionBytes() {
      java.lang.Object ref = languageVersion_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        languageVersion_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string languageVersion = 3;</code>
     * @param value The languageVersion to set.
     * @return This builder for chaining.
     */
    public Builder setLanguageVersion(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      languageVersion_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>string languageVersion = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearLanguageVersion() {
      languageVersion_ = getDefaultInstance().getLanguageVersion();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <code>string languageVersion = 3;</code>
     * @param value The bytes for languageVersion to set.
     * @return This builder for chaining.
     */
    public Builder setLanguageVersionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      languageVersion_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private java.lang.Object tracerVersion_ = "";
    /**
     * <code>string tracerVersion = 4;</code>
     * @return The tracerVersion.
     */
    public java.lang.String getTracerVersion() {
      java.lang.Object ref = tracerVersion_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        tracerVersion_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string tracerVersion = 4;</code>
     * @return The bytes for tracerVersion.
     */
    public com.google.protobuf.ByteString
        getTracerVersionBytes() {
      java.lang.Object ref = tracerVersion_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        tracerVersion_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string tracerVersion = 4;</code>
     * @param value The tracerVersion to set.
     * @return This builder for chaining.
     */
    public Builder setTracerVersion(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      tracerVersion_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>string tracerVersion = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearTracerVersion() {
      tracerVersion_ = getDefaultInstance().getTracerVersion();
      bitField0_ = (bitField0_ & ~0x00000008);
      onChanged();
      return this;
    }
    /**
     * <code>string tracerVersion = 4;</code>
     * @param value The bytes for tracerVersion to set.
     * @return This builder for chaining.
     */
    public Builder setTracerVersionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      tracerVersion_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }

    private java.lang.Object runtimeID_ = "";
    /**
     * <code>string runtimeID = 5;</code>
     * @return The runtimeID.
     */
    public java.lang.String getRuntimeID() {
      java.lang.Object ref = runtimeID_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        runtimeID_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string runtimeID = 5;</code>
     * @return The bytes for runtimeID.
     */
    public com.google.protobuf.ByteString
        getRuntimeIDBytes() {
      java.lang.Object ref = runtimeID_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        runtimeID_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string runtimeID = 5;</code>
     * @param value The runtimeID to set.
     * @return This builder for chaining.
     */
    public Builder setRuntimeID(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      runtimeID_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>string runtimeID = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearRuntimeID() {
      runtimeID_ = getDefaultInstance().getRuntimeID();
      bitField0_ = (bitField0_ & ~0x00000010);
      onChanged();
      return this;
    }
    /**
     * <code>string runtimeID = 5;</code>
     * @param value The bytes for runtimeID to set.
     * @return This builder for chaining.
     */
    public Builder setRuntimeIDBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      runtimeID_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }

    private java.util.List<com.dd.agent.pb.APITraceChunk> chunks_ =
      java.util.Collections.emptyList();
    private void ensureChunksIsMutable() {
      if (!((bitField0_ & 0x00000020) != 0)) {
        chunks_ = new java.util.ArrayList<com.dd.agent.pb.APITraceChunk>(chunks_);
        bitField0_ |= 0x00000020;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.dd.agent.pb.APITraceChunk, com.dd.agent.pb.APITraceChunk.Builder, com.dd.agent.pb.APITraceChunkOrBuilder> chunksBuilder_;

    /**
     * <code>repeated .pb.APITraceChunk chunks = 6;</code>
     */
    public java.util.List<com.dd.agent.pb.APITraceChunk> getChunksList() {
      if (chunksBuilder_ == null) {
        return java.util.Collections.unmodifiableList(chunks_);
      } else {
        return chunksBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .pb.APITraceChunk chunks = 6;</code>
     */
    public int getChunksCount() {
      if (chunksBuilder_ == null) {
        return chunks_.size();
      } else {
        return chunksBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .pb.APITraceChunk chunks = 6;</code>
     */
    public com.dd.agent.pb.APITraceChunk getChunks(int index) {
      if (chunksBuilder_ == null) {
        return chunks_.get(index);
      } else {
        return chunksBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .pb.APITraceChunk chunks = 6;</code>
     */
    public Builder setChunks(
        int index, com.dd.agent.pb.APITraceChunk value) {
      if (chunksBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureChunksIsMutable();
        chunks_.set(index, value);
        onChanged();
      } else {
        chunksBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .pb.APITraceChunk chunks = 6;</code>
     */
    public Builder setChunks(
        int index, com.dd.agent.pb.APITraceChunk.Builder builderForValue) {
      if (chunksBuilder_ == null) {
        ensureChunksIsMutable();
        chunks_.set(index, builderForValue.build());
        onChanged();
      } else {
        chunksBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .pb.APITraceChunk chunks = 6;</code>
     */
    public Builder addChunks(com.dd.agent.pb.APITraceChunk value) {
      if (chunksBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureChunksIsMutable();
        chunks_.add(value);
        onChanged();
      } else {
        chunksBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .pb.APITraceChunk chunks = 6;</code>
     */
    public Builder addChunks(
        int index, com.dd.agent.pb.APITraceChunk value) {
      if (chunksBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureChunksIsMutable();
        chunks_.add(index, value);
        onChanged();
      } else {
        chunksBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .pb.APITraceChunk chunks = 6;</code>
     */
    public Builder addChunks(
        com.dd.agent.pb.APITraceChunk.Builder builderForValue) {
      if (chunksBuilder_ == null) {
        ensureChunksIsMutable();
        chunks_.add(builderForValue.build());
        onChanged();
      } else {
        chunksBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .pb.APITraceChunk chunks = 6;</code>
     */
    public Builder addChunks(
        int index, com.dd.agent.pb.APITraceChunk.Builder builderForValue) {
      if (chunksBuilder_ == null) {
        ensureChunksIsMutable();
        chunks_.add(index, builderForValue.build());
        onChanged();
      } else {
        chunksBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .pb.APITraceChunk chunks = 6;</code>
     */
    public Builder addAllChunks(
        java.lang.Iterable<? extends com.dd.agent.pb.APITraceChunk> values) {
      if (chunksBuilder_ == null) {
        ensureChunksIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, chunks_);
        onChanged();
      } else {
        chunksBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .pb.APITraceChunk chunks = 6;</code>
     */
    public Builder clearChunks() {
      if (chunksBuilder_ == null) {
        chunks_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000020);
        onChanged();
      } else {
        chunksBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .pb.APITraceChunk chunks = 6;</code>
     */
    public Builder removeChunks(int index) {
      if (chunksBuilder_ == null) {
        ensureChunksIsMutable();
        chunks_.remove(index);
        onChanged();
      } else {
        chunksBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .pb.APITraceChunk chunks = 6;</code>
     */
    public com.dd.agent.pb.APITraceChunk.Builder getChunksBuilder(
        int index) {
      return getChunksFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .pb.APITraceChunk chunks = 6;</code>
     */
    public com.dd.agent.pb.APITraceChunkOrBuilder getChunksOrBuilder(
        int index) {
      if (chunksBuilder_ == null) {
        return chunks_.get(index);  } else {
        return chunksBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .pb.APITraceChunk chunks = 6;</code>
     */
    public java.util.List<? extends com.dd.agent.pb.APITraceChunkOrBuilder> 
         getChunksOrBuilderList() {
      if (chunksBuilder_ != null) {
        return chunksBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(chunks_);
      }
    }
    /**
     * <code>repeated .pb.APITraceChunk chunks = 6;</code>
     */
    public com.dd.agent.pb.APITraceChunk.Builder addChunksBuilder() {
      return getChunksFieldBuilder().addBuilder(
          com.dd.agent.pb.APITraceChunk.getDefaultInstance());
    }
    /**
     * <code>repeated .pb.APITraceChunk chunks = 6;</code>
     */
    public com.dd.agent.pb.APITraceChunk.Builder addChunksBuilder(
        int index) {
      return getChunksFieldBuilder().addBuilder(
          index, com.dd.agent.pb.APITraceChunk.getDefaultInstance());
    }
    /**
     * <code>repeated .pb.APITraceChunk chunks = 6;</code>
     */
    public java.util.List<com.dd.agent.pb.APITraceChunk.Builder> 
         getChunksBuilderList() {
      return getChunksFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.dd.agent.pb.APITraceChunk, com.dd.agent.pb.APITraceChunk.Builder, com.dd.agent.pb.APITraceChunkOrBuilder> 
        getChunksFieldBuilder() {
      if (chunksBuilder_ == null) {
        chunksBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.dd.agent.pb.APITraceChunk, com.dd.agent.pb.APITraceChunk.Builder, com.dd.agent.pb.APITraceChunkOrBuilder>(
                chunks_,
                ((bitField0_ & 0x00000020) != 0),
                getParentForChildren(),
                isClean());
        chunks_ = null;
      }
      return chunksBuilder_;
    }

    private com.google.protobuf.MapField<
        java.lang.String, java.lang.String> tags_;
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
        internalGetTags() {
      if (tags_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            TagsDefaultEntryHolder.defaultEntry);
      }
      return tags_;
    }
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
        internalGetMutableTags() {
      if (tags_ == null) {
        tags_ = com.google.protobuf.MapField.newMapField(
            TagsDefaultEntryHolder.defaultEntry);
      }
      if (!tags_.isMutable()) {
        tags_ = tags_.copy();
      }
      bitField0_ |= 0x00000040;
      onChanged();
      return tags_;
    }
    public int getTagsCount() {
      return internalGetTags().getMap().size();
    }
    /**
     * <code>map&lt;string, string&gt; tags = 7;</code>
     */
    @java.lang.Override
    public boolean containsTags(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      return internalGetTags().getMap().containsKey(key);
    }
    /**
     * Use {@link #getTagsMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String> getTags() {
      return getTagsMap();
    }
    /**
     * <code>map&lt;string, string&gt; tags = 7;</code>
     */
    @java.lang.Override
    public java.util.Map<java.lang.String, java.lang.String> getTagsMap() {
      return internalGetTags().getMap();
    }
    /**
     * <code>map&lt;string, string&gt; tags = 7;</code>
     */
    @java.lang.Override
    public /* nullable */
java.lang.String getTagsOrDefault(
        java.lang.String key,
        /* nullable */
java.lang.String defaultValue) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetTags().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, string&gt; tags = 7;</code>
     */
    @java.lang.Override
    public java.lang.String getTagsOrThrow(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetTags().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }
    public Builder clearTags() {
      bitField0_ = (bitField0_ & ~0x00000040);
      internalGetMutableTags().getMutableMap()
          .clear();
      return this;
    }
    /**
     * <code>map&lt;string, string&gt; tags = 7;</code>
     */
    public Builder removeTags(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      internalGetMutableTags().getMutableMap()
          .remove(key);
      return this;
    }
    /**
     * Use alternate mutation accessors instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String>
        getMutableTags() {
      bitField0_ |= 0x00000040;
      return internalGetMutableTags().getMutableMap();
    }
    /**
     * <code>map&lt;string, string&gt; tags = 7;</code>
     */
    public Builder putTags(
        java.lang.String key,
        java.lang.String value) {
      if (key == null) { throw new NullPointerException("map key"); }
      if (value == null) { throw new NullPointerException("map value"); }
      internalGetMutableTags().getMutableMap()
          .put(key, value);
      bitField0_ |= 0x00000040;
      return this;
    }
    /**
     * <code>map&lt;string, string&gt; tags = 7;</code>
     */
    public Builder putAllTags(
        java.util.Map<java.lang.String, java.lang.String> values) {
      internalGetMutableTags().getMutableMap()
          .putAll(values);
      bitField0_ |= 0x00000040;
      return this;
    }

    private java.lang.Object env_ = "";
    /**
     * <code>string env = 8;</code>
     * @return The env.
     */
    public java.lang.String getEnv() {
      java.lang.Object ref = env_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        env_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string env = 8;</code>
     * @return The bytes for env.
     */
    public com.google.protobuf.ByteString
        getEnvBytes() {
      java.lang.Object ref = env_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        env_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string env = 8;</code>
     * @param value The env to set.
     * @return This builder for chaining.
     */
    public Builder setEnv(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      env_ = value;
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }
    /**
     * <code>string env = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearEnv() {
      env_ = getDefaultInstance().getEnv();
      bitField0_ = (bitField0_ & ~0x00000080);
      onChanged();
      return this;
    }
    /**
     * <code>string env = 8;</code>
     * @param value The bytes for env to set.
     * @return This builder for chaining.
     */
    public Builder setEnvBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      env_ = value;
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }

    private java.lang.Object hostname_ = "";
    /**
     * <code>string hostname = 9;</code>
     * @return The hostname.
     */
    public java.lang.String getHostname() {
      java.lang.Object ref = hostname_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        hostname_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string hostname = 9;</code>
     * @return The bytes for hostname.
     */
    public com.google.protobuf.ByteString
        getHostnameBytes() {
      java.lang.Object ref = hostname_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        hostname_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string hostname = 9;</code>
     * @param value The hostname to set.
     * @return This builder for chaining.
     */
    public Builder setHostname(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      hostname_ = value;
      bitField0_ |= 0x00000100;
      onChanged();
      return this;
    }
    /**
     * <code>string hostname = 9;</code>
     * @return This builder for chaining.
     */
    public Builder clearHostname() {
      hostname_ = getDefaultInstance().getHostname();
      bitField0_ = (bitField0_ & ~0x00000100);
      onChanged();
      return this;
    }
    /**
     * <code>string hostname = 9;</code>
     * @param value The bytes for hostname to set.
     * @return This builder for chaining.
     */
    public Builder setHostnameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      hostname_ = value;
      bitField0_ |= 0x00000100;
      onChanged();
      return this;
    }

    private java.lang.Object appVersion_ = "";
    /**
     * <code>string appVersion = 10;</code>
     * @return The appVersion.
     */
    public java.lang.String getAppVersion() {
      java.lang.Object ref = appVersion_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        appVersion_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string appVersion = 10;</code>
     * @return The bytes for appVersion.
     */
    public com.google.protobuf.ByteString
        getAppVersionBytes() {
      java.lang.Object ref = appVersion_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        appVersion_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string appVersion = 10;</code>
     * @param value The appVersion to set.
     * @return This builder for chaining.
     */
    public Builder setAppVersion(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      appVersion_ = value;
      bitField0_ |= 0x00000200;
      onChanged();
      return this;
    }
    /**
     * <code>string appVersion = 10;</code>
     * @return This builder for chaining.
     */
    public Builder clearAppVersion() {
      appVersion_ = getDefaultInstance().getAppVersion();
      bitField0_ = (bitField0_ & ~0x00000200);
      onChanged();
      return this;
    }
    /**
     * <code>string appVersion = 10;</code>
     * @param value The bytes for appVersion to set.
     * @return This builder for chaining.
     */
    public Builder setAppVersionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      appVersion_ = value;
      bitField0_ |= 0x00000200;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:pb.APITracerPayload)
  }

  // @@protoc_insertion_point(class_scope:pb.APITracerPayload)
  private static final com.dd.agent.pb.APITracerPayload DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.dd.agent.pb.APITracerPayload();
  }

  public static com.dd.agent.pb.APITracerPayload getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<APITracerPayload>
      PARSER = new com.google.protobuf.AbstractParser<APITracerPayload>() {
    @java.lang.Override
    public APITracerPayload parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<APITracerPayload> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<APITracerPayload> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.dd.agent.pb.APITracerPayload getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

