// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/resources/protos/trace.proto

package com.dd.agent.pb;

public interface APITracerPayloadOrBuilder extends
    // @@protoc_insertion_point(interface_extends:pb.APITracerPayload)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string containerID = 1;</code>
   * @return The containerID.
   */
  java.lang.String getContainerID();
  /**
   * <code>string containerID = 1;</code>
   * @return The bytes for containerID.
   */
  com.google.protobuf.ByteString
      getContainerIDBytes();

  /**
   * <code>string languageName = 2;</code>
   * @return The languageName.
   */
  java.lang.String getLanguageName();
  /**
   * <code>string languageName = 2;</code>
   * @return The bytes for languageName.
   */
  com.google.protobuf.ByteString
      getLanguageNameBytes();

  /**
   * <code>string languageVersion = 3;</code>
   * @return The languageVersion.
   */
  java.lang.String getLanguageVersion();
  /**
   * <code>string languageVersion = 3;</code>
   * @return The bytes for languageVersion.
   */
  com.google.protobuf.ByteString
      getLanguageVersionBytes();

  /**
   * <code>string tracerVersion = 4;</code>
   * @return The tracerVersion.
   */
  java.lang.String getTracerVersion();
  /**
   * <code>string tracerVersion = 4;</code>
   * @return The bytes for tracerVersion.
   */
  com.google.protobuf.ByteString
      getTracerVersionBytes();

  /**
   * <code>string runtimeID = 5;</code>
   * @return The runtimeID.
   */
  java.lang.String getRuntimeID();
  /**
   * <code>string runtimeID = 5;</code>
   * @return The bytes for runtimeID.
   */
  com.google.protobuf.ByteString
      getRuntimeIDBytes();

  /**
   * <code>repeated .pb.APITraceChunk chunks = 6;</code>
   */
  java.util.List<com.dd.agent.pb.APITraceChunk> 
      getChunksList();
  /**
   * <code>repeated .pb.APITraceChunk chunks = 6;</code>
   */
  com.dd.agent.pb.APITraceChunk getChunks(int index);
  /**
   * <code>repeated .pb.APITraceChunk chunks = 6;</code>
   */
  int getChunksCount();
  /**
   * <code>repeated .pb.APITraceChunk chunks = 6;</code>
   */
  java.util.List<? extends com.dd.agent.pb.APITraceChunkOrBuilder> 
      getChunksOrBuilderList();
  /**
   * <code>repeated .pb.APITraceChunk chunks = 6;</code>
   */
  com.dd.agent.pb.APITraceChunkOrBuilder getChunksOrBuilder(
      int index);

  /**
   * <code>map&lt;string, string&gt; tags = 7;</code>
   */
  int getTagsCount();
  /**
   * <code>map&lt;string, string&gt; tags = 7;</code>
   */
  boolean containsTags(
      java.lang.String key);
  /**
   * Use {@link #getTagsMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, java.lang.String>
  getTags();
  /**
   * <code>map&lt;string, string&gt; tags = 7;</code>
   */
  java.util.Map<java.lang.String, java.lang.String>
  getTagsMap();
  /**
   * <code>map&lt;string, string&gt; tags = 7;</code>
   */
  /* nullable */
java.lang.String getTagsOrDefault(
      java.lang.String key,
      /* nullable */
java.lang.String defaultValue);
  /**
   * <code>map&lt;string, string&gt; tags = 7;</code>
   */
  java.lang.String getTagsOrThrow(
      java.lang.String key);

  /**
   * <code>string env = 8;</code>
   * @return The env.
   */
  java.lang.String getEnv();
  /**
   * <code>string env = 8;</code>
   * @return The bytes for env.
   */
  com.google.protobuf.ByteString
      getEnvBytes();

  /**
   * <code>string hostname = 9;</code>
   * @return The hostname.
   */
  java.lang.String getHostname();
  /**
   * <code>string hostname = 9;</code>
   * @return The bytes for hostname.
   */
  com.google.protobuf.ByteString
      getHostnameBytes();

  /**
   * <code>string appVersion = 10;</code>
   * @return The appVersion.
   */
  java.lang.String getAppVersion();
  /**
   * <code>string appVersion = 10;</code>
   * @return The bytes for appVersion.
   */
  com.google.protobuf.ByteString
      getAppVersionBytes();
}
